import pathlib
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]
APP_TSX = ROOT / "frontend" / "src" / "app.tsx"
API_TS = ROOT / "frontend" / "src" / "lib" / "api.ts"
TRANSCRIPT_TSX = ROOT / "frontend" / "src" / "lib" / "transcript.tsx"
MARKDOWN_TSX = ROOT / "frontend" / "src" / "lib" / "markdown.tsx"
TYPES_TS = ROOT / "frontend" / "src" / "lib" / "types.ts"
STYLES_CSS = ROOT / "frontend" / "src" / "styles.css"


class NovaPreviewSourceTest(unittest.TestCase):
    def test_new_session_cwd_uses_clickable_folder_autocomplete(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        api_source = API_TS.read_text(encoding="utf-8")
        types_source = TYPES_TS.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn("export type CwdSuggestion = {", types_source)
        self.assertIn("export type CwdSuggestionsResponse = {", types_source)
        self.assertIn("fetchCwdSuggestions(query: string, limit = 12): Promise<CwdSuggestionsResponse>", api_source)
        self.assertIn("/api/cwd_suggestions?q=${encodeURIComponent(query)}&limit=${encodeURIComponent(String(limit))}", api_source)
        self.assertIn("const [newSessionCwdSuggestions, setNewSessionCwdSuggestions] = useState<CwdSuggestion[]>([]);", app_source)
        self.assertIn("const newSessionCwdSuggestionChoices = useMemo(() => newSessionCwdSuggestions.slice(0, 12), [newSessionCwdSuggestions]);", app_source)
        self.assertIn("const newSessionCwdInputRef = useRef<HTMLInputElement | null>(null);", app_source)
        self.assertIn("async function loadCwdSuggestions(query: string)", app_source)
        self.assertIn("function applyNewSessionCwdSuggestion(suggestion: CwdSuggestion)", app_source)
        self.assertIn("function handleNewSessionCwdKeyDown(event: KeyboardEvent)", app_source)
        self.assertIn('className="cwdAutocomplete"', app_source)
        self.assertIn('role="combobox"', app_source)
        self.assertIn('id="new-session-cwd-suggestions" role="listbox"', app_source)
        self.assertIn('className={`cwdSuggestion${index === newSessionCwdSuggestionIndex ? " active" : ""}`}', app_source)
        self.assertIn("No matching folders.", app_source)
        self.assertNotIn('list="recent-cwds"', app_source)
        self.assertNotIn('<datalist id="recent-cwds">', app_source)
        self.assertIn(".cwdAutocomplete {\n  position: relative;", css_source)
        self.assertIn(".cwdSuggestions {\n  position: absolute;", css_source)
        self.assertIn(".cwdSuggestion.active,\n.cwdSuggestion:hover {", css_source)
        self.assertIn(".cwdSuggestionBadge {\n  flex: 0 0 auto;", css_source)

    def test_resume_choices_prefer_alias_then_last_user_message(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        types_source = TYPES_TS.read_text(encoding="utf-8")
        self.assertIn("last_user_message?: string;", types_source)
        self.assertNotIn("first_user_message?: string;", types_source)
        self.assertIn("candidate.alias || candidate.last_user_message || candidate.session_id", app_source)
        self.assertNotIn("candidate.alias || candidate.first_user_message || candidate.session_id", app_source)

    def test_new_session_defaults_to_tmux_when_available(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("setNewSessionTmux(tmuxAvailable);", source)
        self.assertIn("create_in_tmux: tmuxAvailable && newSessionTmux", source)

    def test_new_session_selection_updates_ref_before_send(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("function selectSession(sessionId: string) {", source)
        self.assertIn("selectedSessionRef.current = sessionId;", source)
        self.assertIn("selectSession(found.session_id);", source)

    def test_new_session_dialog_closes_before_background_follow(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("const composerInputRef = useRef<HTMLTextAreaElement | null>(null);", source)
        self.assertIn("function focusComposerInput()", source)
        self.assertIn("async function followCreatedSession(brokerPid: number)", source)
        self.assertIn("function promoteOpenedSession(session: SessionSummary, previousSessions: SessionSummary[], nextSessions: SessionSummary[])", source)
        self.assertIn("promoteOpenedSession(found, sessions, ordered);", source)
        self.assertIn("setNewSessionOpen(false);\n      void followCreatedSession(result.broker_pid)", source)
        self.assertIn("ref={composerInputRef}", source)

    def test_rename_session_control_is_wired_to_api(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        api_source = API_TS.read_text(encoding="utf-8")
        self.assertIn("renameSession(sessionId: string, name: string)", api_source)
        self.assertIn("/rename", api_source)
        self.assertIn("function openRenameDialog(targetSession = selectedSession)", app_source)
        self.assertIn("const [renameSessionId, setRenameSessionId] = useState(\"\");", app_source)
        self.assertIn("const renameTargetSession = useMemo(", app_source)
        self.assertIn("setRenameSessionId(targetSession.session_id);", app_source)
        self.assertIn("void handleRenameSession()", app_source)
        self.assertIn('className="formGrid"', app_source)
        self.assertIn('onSubmit={(event) => {', app_source)
        self.assertIn('event.preventDefault();\n                void handleRenameSession();', app_source)
        self.assertIn('className="primary" type="submit" disabled={renameBusy}', app_source)
        self.assertIn('className="icon-btn"', app_source)
        self.assertIn('{icon("edit")}', app_source)
        self.assertNotIn("<span>Rename</span>", app_source)
        self.assertIn('title={selectedSession ? "Rename session" : "No session selected"}', app_source)

    def test_send_has_visible_pending_state_and_busy_queue_path(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        transcript_source = TRANSCRIPT_TSX.read_text(encoding="utf-8")
        self.assertIn("const [sending, setSending] = useState(false);", source)
        self.assertIn('type BusySubmitMode = "queue" | "interrupt";', source)
        self.assertIn("const [busySubmitMode, setBusySubmitMode] = useState<BusySubmitMode>(() => readBusySubmitMode());", source)
        self.assertIn("function mergeTranscriptEvents(current: UiTranscriptEvent[], incoming: UiTranscriptEvent[])", transcript_source)
        self.assertIn("let localEvent: UiTranscriptEvent | null = null;", source)
        self.assertIn("if (!shouldQueue) {\n      localEvent = {", source)
        self.assertIn('id: `local-user-${Date.now()}`', source)
        self.assertIn('meta: "sending"', source)
        self.assertNotIn('meta: shouldQueue ? "queued" : "sending"', source)
        self.assertIn("const composerSessionBusy = Boolean(awaitingAssistantReply || busy || selectedSession?.busy);", source)
        self.assertIn('const shouldQueue = composerSessionBusy && busySubmitMode === "queue";', source)
        self.assertIn('const shouldInterrupt = composerSessionBusy && busySubmitMode === "interrupt";', source)
        self.assertIn("await api.enqueueMessage(sessionId, text);", source)
        self.assertNotIn("meta: `queued${response.queue_len", source)
        self.assertIn("if (shouldInterrupt) await api.interrupt(sessionId);", source)
        self.assertIn("await api.sendMessage(sessionId, text);", source)
        self.assertIn("function handleComposerKeyDown(event: KeyboardEvent)", source)
        self.assertIn('if (event.key !== "Enter" || event.shiftKey || event.isComposing) return;', source)
        self.assertIn("event.preventDefault();\n    void handleSend();", source)
        self.assertIn("onKeyDown={handleComposerKeyDown}", source)
        self.assertIn('aria-label="Busy send mode"', source)
        self.assertIn('onClick={() => setBusySubmitMode("queue")}', source)
        self.assertIn('onClick={() => setBusySubmitMode("interrupt")}', source)
        self.assertIn('title={sending ? "Sending…" : composerSessionBusy && busySubmitMode === "queue" ? "Queue" : composerSessionBusy ? "Interrupt and send" : "Send"}', source)
        self.assertIn("disabled={sending || !selectedSessionId}", source)

    def test_composer_drafts_are_scoped_per_session_and_marked_in_sidebar(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn('const SESSION_DRAFTS_KEY = "codoxear.nova.sessionDrafts";', app_source)
        self.assertIn("function readStoredSessionDrafts()", app_source)
        self.assertIn("const [sessionDrafts, setSessionDrafts] = useState<Record<string, string>>(() => readStoredSessionDrafts());", app_source)
        self.assertIn('const composerText = selectedSessionId ? sessionDrafts[selectedSessionId] || "" : "";', app_source)
        self.assertIn("function setSessionDraft(sessionId: string, text: string)", app_source)
        self.assertIn('writeLocalStorage(SESSION_DRAFTS_KEY, Object.keys(sessionDrafts).length ? JSON.stringify(sessionDrafts) : null);', app_source)
        self.assertIn('setSessionDraft(sessionId, "");', app_source)
        self.assertIn('setSessionDraft(selectedSessionId, (event.currentTarget as HTMLTextAreaElement).value)', app_source)
        self.assertIn('const hasDraft = Boolean((sessionDrafts[session.session_id] || "").trim());', app_source)
        self.assertIn('className="workspaceDraftMark"', app_source)
        self.assertIn('title="Draft saved" aria-label="Draft saved"', app_source)
        self.assertIn('.workspaceDraftMark {', css_source)
        self.assertIn('background: rgba(37, 99, 235, 0.88);', css_source)

    def test_queue_preview_renders_above_composer(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn("const queuePreviewItems = useMemo(() => queueItems.slice(0, 3), [queueItems]);", source)
        self.assertIn("setQueueLen(items.length);", source)
        self.assertIn("void loadQueue(sessionId);", source)
        self.assertIn("function openQueueModal()", source)
        self.assertIn('className="queuePreview"', source)
        self.assertIn("<span>Queued messages</span>", source)
        self.assertIn('{queuePreviewItems.map((item, index) => (', source)
        self.assertIn('onClick={() => openQueueModal()}', source)
        self.assertIn(".queuePreview {\n  width: min(920px, 100%);", css_source)
        self.assertIn(".queuePreviewItem {\n  display: grid;", css_source)

    def test_transcript_renders_markdown_blocks(self) -> None:
        transcript_source = TRANSCRIPT_TSX.read_text(encoding="utf-8")
        markdown_source = MARKDOWN_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn('import { MarkdownBlock } from "./markdown";', transcript_source)
        self.assertNotIn('import { PretextParagraph } from "./pretext";', transcript_source)
        self.assertIn('className="message-body markdown-body"', transcript_source)
        self.assertIn("export function markdownToHtml(text: string)", markdown_source)
        self.assertIn("function renderInlineMarkdown(value: string): string", markdown_source)
        self.assertIn("function renderTable(lines: string[], start: number)", markdown_source)
        self.assertIn("function blockquoteLine(line: string)", markdown_source)
        self.assertIn('out.push(`<blockquote>${renderMarkdownBlocks(quoteLines.join("\\n"))}</blockquote>`);', markdown_source)
        self.assertIn('return `<pre><code${langAttr}>${escapeHtml(chunk.value)}</code></pre>`;', markdown_source)
        self.assertIn('dangerouslySetInnerHTML={{ __html: markdownToHtml(text) }}', markdown_source)
        self.assertIn(".markdown-body h1,\n.markdown-body h2,", css_source)
        self.assertIn(".markdown-body blockquote {\n  border-left: 3px solid var(--border);", css_source)
        self.assertIn(".markdown-body pre code {\n  display: block;", css_source)
        self.assertIn(".md-table-wrap {\n  max-width: 100%;", css_source)

    def test_close_session_control_uses_delete_api(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        api_source = API_TS.read_text(encoding="utf-8")
        self.assertIn("deleteSession(sessionId: string)", api_source)
        self.assertIn("/delete", api_source)
        self.assertIn("async function handleCloseSession(targetSession = selectedSession)", app_source)
        self.assertIn("await api.deleteSession(sessionId);", app_source)
        self.assertIn('title={selectedSession ? "Close session" : "No session selected"}', app_source)
        self.assertIn('className="icon-btn danger"', app_source)

    def test_tmux_copy_handles_missing_clipboard_api(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("function copyTextViaSelection(text: string)", source)
        self.assertIn('typeof document.execCommand !== "function"', source)
        self.assertIn('document.execCommand("copy")', source)
        self.assertIn("async function copyToClipboard(text: string)", source)
        self.assertIn("navigator.clipboard && typeof navigator.clipboard.writeText === \"function\"", source)
        self.assertIn("await copyToClipboard(tmuxCommand);", source)
        self.assertNotIn("await navigator.clipboard.writeText(tmuxCommand);", source)
        self.assertIn('title={tmuxCommand || "No tmux attach command for this session"}', source)
        self.assertIn('{icon("terminal")}', source)
        self.assertEqual(source.count('{icon("tmux")}'), 0)

    def test_topbar_tool_toggle_uses_wrench_icon(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn('case "wrench":', source)
        self.assertIn('title={showTools ? "Hide tool calls" : "Show tool calls"}', source)
        self.assertIn('{icon("wrench")}', source)
        self.assertIn("setShowTools((current) => !current)", source)

    def test_topbar_uses_stable_session_status_not_polling_label(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("const topSessionStatus = useMemo(() => {", source)
        self.assertIn('if (queueLen) return `queue ${queueLen}`;', source)
        self.assertIn('if (awaitingAssistantReply || busy || selectedSession.busy) return "working";', source)
        self.assertIn('if (sessionIsStarting(selectedSession)) return "starting";', source)
        self.assertIn('const queuedWaitingStatus = Boolean(selectedSession && queueLen && !closingSession && !sending && sessionIsQueuedWaiting(selectedSession) && !(awaitingAssistantReply || busy || selectedSession.busy));', source)
        self.assertIn('topSessionStatus === "working" || topSessionStatus === "starting"', source)
        self.assertIn('? "status-chip working"', source)
        self.assertIn('? "status-chip waiting"', source)
        self.assertIn('<span className={topSessionStatusClass}>{topSessionStatus}</span>', source)
        self.assertIn(".topMeta > .status-chip.working {\n  margin-left: 3px;\n}", STYLES_CSS.read_text(encoding="utf-8"))
        self.assertIn(".status-chip.waiting {\n  gap: 6px;", STYLES_CSS.read_text(encoding="utf-8"))
        self.assertNotIn("connectionLabel", source)
        self.assertNotIn("loading transcript", source)

    def test_topbar_context_chip_is_labeled_as_estimate(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("function formatTokenCount(value: number)", source)
        self.assertIn('label: `Ctx est ${formatTokenCount(tokensInContext)}/${formatTokenCount(contextWindow)}`', source)
        self.assertIn('Usage comes from the latest token update. Context window size may be inferred from model metadata for some backends.', source)
        self.assertIn('title={tokenSummary.title}', source)
        self.assertNotIn('return `${tokensInContext}/${contextWindow} (${Math.round(percentRemaining)}% left)`;', source)

    def test_chat_bottom_shows_working_indicator(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn('function WorkingIndicator(props: { label: string; tone?: "working" | "waiting" })', app_source)
        self.assertIn('role="status" aria-live="polite" aria-label={label}', app_source)
        self.assertIn('className={`msg event-working workingRow${tone === "waiting" ? " is-waiting" : ""}`}', app_source)
        self.assertIn('<div className="message-side is-hidden" />', app_source)
        self.assertIn('<div className="message-main">', app_source)
        self.assertIn('topSessionStatus === "sending" ? "Sending"', app_source)
        self.assertIn('topSessionStatus === "starting" ? "Starting"', app_source)
        self.assertIn('topSessionStatus === "working" ? "Working"', app_source)
        self.assertIn('const workingIndicatorTone = queuedWaitingStatus ? "waiting" : "working";', app_source)
        self.assertIn("{workingIndicatorLabel ? <WorkingIndicator label={workingIndicatorLabel} tone={workingIndicatorTone} /> : null}", app_source)
        self.assertIn("!visibleTranscript.length && !workingIndicatorLabel", app_source)
        self.assertIn("workingIndicatorLabel,\n    ].join(\":\");", app_source)
        self.assertIn("}, [selectedSessionId, visibleTranscript, workingIndicatorLabel]);", app_source)
        self.assertIn(".workingRow {\n  padding: 4px 0 22px;", css_source)
        self.assertIn(".workingRow .message-main {\n  grid-column: 2;", css_source)
        self.assertIn(".workingRow.is-waiting .workingIndicator,\n.workingRow.is-waiting .workingLabel {", css_source)
        self.assertIn(".workingDots {\n  display: inline-flex;", css_source)
        self.assertIn(".workingDot {\n  width: 5px;", css_source)
        self.assertIn("@keyframes workingDot", css_source)
        self.assertIn(".workingRow {\n    padding: 4px 0 18px;", css_source)
        self.assertIn(".workingRow .message-main,\n  .workingIndicator {\n    grid-column: 1;", css_source)

    def test_live_polling_does_not_clear_older_history_state(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn('if (Object.prototype.hasOwnProperty.call(data, "history_cursor")) {', source)
        self.assertIn('historyCursorRef.current = data.history_cursor ?? null;', source)
        self.assertIn('setHistoryCursor(historyCursorRef.current);', source)
        self.assertIn('if (Object.prototype.hasOwnProperty.call(data, "has_older")) {', source)
        self.assertIn('setHasOlder(Boolean(data.has_older));', source)
        self.assertNotIn('historyCursorRef.current = data.history_cursor ?? null;\n    setLiveCursor(liveCursorRef.current);', source)
        self.assertNotIn('setHistoryCursor(historyCursorRef.current);\n    setHasOlder(Boolean(data.has_older));', source)

    def test_load_older_button_only_shows_at_transcript_top_boundary(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        older_btn_block = css_source.split(".olderBtn {", 1)[1].split("}\n", 1)[0]
        self.assertIn("const CHAT_HISTORY_TOP_THRESHOLD_PX = 16;", app_source)
        self.assertIn("function isNearHistoryTop(element: HTMLElement)", app_source)
        self.assertIn("return element.scrollTop <= CHAT_HISTORY_TOP_THRESHOLD_PX;", app_source)
        self.assertIn("const [historyTopBoundaryReached, setHistoryTopBoundaryReached] = useState(true);", app_source)
        self.assertIn("setHistoryTopBoundaryReached(isNearHistoryTop(element));", app_source)
        self.assertIn("window.cancelAnimationFrame(raf);", app_source)
        self.assertIn("}, [selectedSessionId, hasOlder, visibleTranscript.length, loadingOlder, workingIndicatorLabel]);", app_source)
        self.assertIn('{hasOlder && historyTopBoundaryReached ? (', app_source)
        self.assertIn(".olderBtn {\n  display: block;", css_source)
        self.assertNotIn("position: sticky;", older_btn_block)
        self.assertNotIn("top: 10px;", older_btn_block)
        self.assertNotIn("z-index: 2;", older_btn_block)

    def test_load_older_jumps_to_previous_user_message(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        transcript_source = TRANSCRIPT_TSX.read_text(encoding="utf-8")
        self.assertIn("const CHAT_HISTORY_JUMP_OFFSET_PX = 24;", app_source)
        self.assertIn("function olderHistoryJumpTarget(events: UiTranscriptEvent[])", app_source)
        self.assertIn('if (events[index].kind === "user") return events[index].id;', app_source)
        self.assertIn('return events[events.length - 1]?.id || "";', app_source)
        self.assertIn("function scrollChatEventIntoView(eventId: string, offsetPx = CHAT_HISTORY_JUMP_OFFSET_PX)", app_source)
        self.assertIn('const target = Array.from(element.querySelectorAll<HTMLElement>("[data-event-id]"))', app_source)
        self.assertIn('const jumpTargetId = olderHistoryJumpTarget(older);', app_source)
        self.assertIn('window.requestAnimationFrame(() => {\n          scrollChatEventIntoView(jumpTargetId);\n        });', app_source)
        self.assertIn('data-event-id={event.id}', transcript_source)

    def test_topbar_sidebar_toggle_collapses_left_navigation(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn("const [sidebarCollapsed, setSidebarCollapsed] = useState(false);", app_source)
        self.assertIn("--sidebar-w: clamp(280px, 24vw, 360px);", css_source)
        self.assertIn("--sidebar-resizer-w: 10px;", css_source)
        self.assertIn('sidebarCollapsed ? " sidebarCollapsed" : ""', app_source)
        self.assertIn('title={sidebarCollapsed ? "Show sidebar" : "Hide sidebar"}', app_source)
        self.assertIn("aria-pressed={sidebarCollapsed}", app_source)
        self.assertIn("onClick={() => setSidebarCollapsed((current) => !current)}", app_source)
        self.assertNotIn('title="Sidebar structure now follows the legacy station" disabled', app_source)
        self.assertIn(".app.sidebarCollapsed,\n.app.sidebarCollapsed.withRail {\n  grid-template-columns: minmax(0, 1fr);", css_source)
        self.assertIn(".app.sidebarCollapsed .sidebar,\n.app.sidebarCollapsed .sidebarResizer {\n  display: none;", css_source)

    def test_sidebar_supports_drag_resize_and_persists_width(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn('const SIDEBAR_WIDTH_KEY = "codoxear.nova.sidebar.width";', app_source)
        self.assertIn("const SIDEBAR_MIN_WIDTH_PX = 240;", app_source)
        self.assertIn("const SIDEBAR_MAX_WIDTH_PX = 520;", app_source)
        self.assertIn("const SIDEBAR_RESIZER_WIDTH_PX = 10;", app_source)
        self.assertIn("const DETAIL_RAIL_WIDTH_PX = 360;", app_source)
        self.assertIn("const DETAIL_RAIL_STACK_BREAKPOINT_PX = 1080;", app_source)
        self.assertIn("function clampSidebarWidth(width: number, viewportWidth = window.innerWidth)", app_source)
        self.assertIn("function readStoredSidebarWidth()", app_source)
        self.assertIn("const [sidebarWidth, setSidebarWidth] = useState<number | null>(() => readStoredSidebarWidth());", app_source)
        self.assertIn("const [sidebarResizing, setSidebarResizing] = useState(false);", app_source)
        self.assertIn("const appRef = useRef<HTMLDivElement | null>(null);", app_source)
        self.assertIn("const sidebarRef = useRef<HTMLElement | null>(null);", app_source)
        self.assertIn("function sidebarRailWidth(viewportWidth = window.innerWidth)", app_source)
        self.assertIn("function currentSidebarLayoutWidth(viewportWidth = window.innerWidth)", app_source)
        self.assertIn("function handleSidebarResizeStart(event: SidebarPointerEvent)", app_source)
        self.assertIn("window.addEventListener(\"pointermove\", onPointerMove);", app_source)
        self.assertIn("window.addEventListener(\"pointerup\", onPointerUp);", app_source)
        self.assertIn("writeLocalStorage(SIDEBAR_WIDTH_KEY, sidebarWidth == null ? null : String(Math.round(sidebarWidth)));", app_source)
        self.assertIn('className="sidebarResizer"', app_source)
        self.assertIn('role="separator"', app_source)
        self.assertIn('aria-label="Resize sidebar"', app_source)
        self.assertIn('onPointerDown={handleSidebarResizeStart}', app_source)
        self.assertIn('ref={appRef}', app_source)
        self.assertIn('style={appStyle}', app_source)
        self.assertIn('sidebarResizing ? " sidebarResizing" : ""', app_source)
        self.assertIn("clampSidebarWidth(sidebarResizeStartWidthRef.current + delta, currentSidebarLayoutWidth())", app_source)
        self.assertIn("const onResize = () => setSidebarWidth((current) => (current == null ? null : clampSidebarWidth(current, currentSidebarLayoutWidth())));", app_source)
        self.assertIn("onResize();", app_source)
        self.assertIn("grid-template-columns: var(--sidebar-w) var(--sidebar-resizer-w) minmax(0, 1fr);", css_source)
        self.assertIn(".sidebar {\n  display: flex;\n  flex-direction: column;\n  width: 100%;\n  min-width: 0;", css_source)
        self.assertIn(".sidebarResizer {\n  position: relative;", css_source)
        self.assertIn("cursor: col-resize;", css_source)
        self.assertIn(".workspaceGroupMeta {\n  min-width: 0;", css_source)
        self.assertIn(".sidebarResizer:hover::before,\n.app.sidebarResizing .sidebarResizer::before {", css_source)

    def test_settings_can_edit_codex_config_toml(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        api_source = API_TS.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn("CodexConfigResponse", api_source)
        self.assertIn("RestartServiceResponse", api_source)
        self.assertIn('"/api/settings/codex_config"', api_source)
        self.assertIn('"/api/settings/restart_service"', api_source)
        self.assertIn("fetchCodexConfig(): Promise<CodexConfigResponse>", api_source)
        self.assertIn("saveCodexConfig(text: string): Promise<CodexConfigResponse>", api_source)
        self.assertIn("restartService(): Promise<RestartServiceResponse>", api_source)
        self.assertIn("const [codexConfig, setCodexConfig] = useState<CodexConfigResponse | null>(null);", app_source)
        self.assertIn("const [codexConfigText, setCodexConfigText] = useState(\"\");", app_source)
        self.assertIn("const [serviceRestarting, setServiceRestarting] = useState(false);", app_source)
        self.assertIn("const [settingsLoadError, setSettingsLoadError] = useState(\"\");", app_source)
        self.assertIn("const displayedVoiceSettings = voiceSettings || EMPTY_VOICE_SETTINGS;", app_source)
        self.assertIn("const settingsInitialLoading = voiceSettingsLoading && !voiceSettings && !codexConfig;", app_source)
        self.assertIn("const [voiceResult, notificationsResult, configResult] = await Promise.allSettled(", app_source)
        self.assertIn("void syncMobilePushState(loadedNotifications, loadedVoice.notifications.vapid_public_key);", app_source)
        self.assertIn("setSettingsLoadError(errors.join(\" · \"));", app_source)
        self.assertIn("{settingsInitialLoading ? (", app_source)
        self.assertIn("settingsLoadError ? (", app_source)
        self.assertIn("Retry", app_source)
        self.assertIn("async function reloadCodexConfig()", app_source)
        self.assertIn("async function saveCodexConfig()", app_source)
        self.assertIn("async function waitForRestartedService(previousServerPid: number)", app_source)
        self.assertIn("async function restartLocalService()", app_source)
        self.assertIn("const restart = await api.restartService();", app_source)
        self.assertIn("if (status.server_pid !== previousServerPid)", app_source)
        self.assertIn('await api.saveCodexConfig(codexConfigText);', app_source)
        self.assertIn("<div className=\"detailSectionHeader\">Codex config.toml</div>", app_source)
        self.assertIn('className="settingsPath"', app_source)
        self.assertIn('className="configTextarea"', app_source)
        self.assertIn("Save config.toml", app_source)
        self.assertIn("Restart service", app_source)
        self.assertIn("provider changes are reloaded", app_source)
        self.assertIn(".configTextarea {\n  min-height: 280px;", css_source)
        self.assertIn(".settingsPath {\n  padding: 8px 10px;", css_source)

    def test_settings_can_switch_between_dark_and_light_theme(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn('const THEME_MODE_KEY = "codoxear.nova.theme";', app_source)
        self.assertIn('type ThemeMode = "dark" | "light";', app_source)
        self.assertIn("function readThemeMode(): ThemeMode", app_source)
        self.assertIn("const [themeMode, setThemeMode] = useState<ThemeMode>(() => readThemeMode());", app_source)
        self.assertIn("document.documentElement.dataset.theme = themeMode;", app_source)
        self.assertIn('writeLocalStorage(THEME_MODE_KEY, themeMode === "light" ? "light" : null);', app_source)
        self.assertIn('<div className="detailSectionHeader">Appearance</div>', app_source)
        self.assertIn('className={`themeChoice${themeMode === "dark" ? " active" : ""}`}', app_source)
        self.assertIn('onClick={() => setThemeMode("light")}', app_source)
        self.assertIn(':root[data-theme="light"] {', css_source)
        self.assertIn("--bg: #eef4f8;", css_source)
        self.assertIn(':root[data-theme="light"] body {\n  background: var(--bg);', css_source)
        self.assertIn(".themePicker {\n  display: grid;", css_source)
        self.assertIn(':root[data-theme="light"] .sidebar,\n:root[data-theme="light"] .detailRail,', css_source)

    def test_sidebar_footer_does_not_show_help_button(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertNotIn("helpOpen", app_source)
        self.assertNotIn("setHelpOpen", app_source)
        self.assertNotIn('{icon("help")}', app_source)
        self.assertNotIn(">Help<", app_source)
        self.assertNotIn(".helpGrid", css_source)

    def test_new_session_working_status_marks_startup_and_awaiting_reply(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn("function sessionIsStarting(session: SessionSummary | null)", app_source)
        self.assertIn("function sessionIsQueuedWaiting(session: SessionSummary | null)", app_source)
        self.assertIn('if (sessionIsStarting(session)) return "starting";', app_source)
        self.assertIn("const awaitingAssistantReply = useMemo(() => {", app_source)
        self.assertIn("return latestUserTs > latestAssistantTs;", app_source)
        self.assertIn('sessionIsQueuedWaiting(session) ? "waiting" : session.busy || sessionIsStarting(session) ? "running" : "idle"', app_source)
        self.assertIn(".status-chip.working", css_source)
        self.assertIn("background: rgba(22, 163, 74, 0.14);", css_source)
        self.assertIn("color: rgba(21, 128, 61, 0.92);", css_source)
        self.assertIn("background: #16a34a;", css_source)
        self.assertIn(".status-dot.waiting {", css_source)
        self.assertIn("@keyframes breathe-dot-waiting", css_source)

    def test_sidebar_preview_uses_latest_user_message(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        transcript_source = TRANSCRIPT_TSX.read_text(encoding="utf-8")
        self.assertIn("function previewFromEvents(events: UiTranscriptEvent[])", transcript_source)
        self.assertIn('if (event.kind !== "user") continue;', transcript_source)
        self.assertNotIn('if (event.kind !== "user" && event.kind !== "assistant") continue;', transcript_source)
        self.assertIn("setSessionLastLines((current) => ({ ...current, [sessionId]: previewFromEvents(nextEvents) || current[sessionId] || \"\" }));", source)
        self.assertIn("setSessionLastLines((prev) => ({ ...prev, [sessionId]: previewFromEvents(merged) || prev[sessionId] || \"\" }));", source)

    def test_sidebar_workspaces_and_sessions_are_draggable_and_persist_order(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn('const SIDEBAR_WORKSPACE_ORDER_KEY = "codoxear.nova.sidebar.workspaceOrder";', app_source)
        self.assertIn('const SIDEBAR_SESSION_ORDER_KEY = "codoxear.nova.sidebar.sessionOrder";', app_source)
        self.assertIn("function applyStoredOrder<T>(items: T[], order: string[], keyForItem: (item: T) => string)", app_source)
        self.assertIn('type SidebarDropPosition = "before" | "after";', app_source)
        self.assertIn("type SidebarDropIndicator =", app_source)
        self.assertIn('function moveOrderedKey(keys: string[], source: string, target: string, position: SidebarDropPosition = "before")', app_source)
        self.assertIn("function prependOrderedKey(keys: string[], key: string)", app_source)
        self.assertIn("function appendOrderedKey(keys: string[], key: string)", app_source)
        self.assertIn("function insertOrderedKeyAfterAnchors(keys: string[], key: string, anchors: string[])", app_source)
        self.assertIn("function partitionImportantFirst<T>(items: T[], isImportant: (item: T) => boolean)", app_source)
        self.assertIn("function uniqueStringsInOrder(values: string[])", app_source)
        self.assertIn("function dropPositionFromEvent(event: SidebarDragEvent): SidebarDropPosition", app_source)
        self.assertIn("const [workspaceOrder, setWorkspaceOrder] = useState<string[]>(() => readStoredStringList(SIDEBAR_WORKSPACE_ORDER_KEY));", app_source)
        self.assertIn("const [sessionOrderByWorkspace, setSessionOrderByWorkspace] = useState<SidebarSessionOrder>(() => readStoredSessionOrder());", app_source)
        self.assertIn("const [sidebarDropIndicator, setSidebarDropIndicator] = useState<SidebarDropIndicator | null>(null);", app_source)
        self.assertIn("applyStoredOrder(fallbackSortedGroups, workspaceOrder, (group) => group.key)", app_source)
        self.assertIn("sessions: partitionImportantFirst(", app_source)
        self.assertIn("return partitionImportantFirst(orderedGroups, (group) => group.sessions.some((session) => sessionIsImportant(session)));", app_source)
        self.assertIn("function handleWorkspaceDragStart(event: SidebarDragEvent, workspaceKey: string)", app_source)
        self.assertIn("function handleWorkspaceDragOver(event: SidebarDragEvent, targetWorkspaceKey: string)", app_source)
        self.assertIn("function handleWorkspaceDrop(event: SidebarDragEvent, targetWorkspaceKey: string)", app_source)
        self.assertIn("function handleSessionDragStart(event: SidebarDragEvent, workspaceKey: string, sessionId: string)", app_source)
        self.assertIn("function handleSessionDragOver(event: SidebarDragEvent, workspaceKey: string, targetSessionId: string)", app_source)
        self.assertIn("function handleSessionDrop(event: SidebarDragEvent, workspaceKey: string, targetSessionId: string)", app_source)
        self.assertIn('setSidebarDropIndicator({ kind: "workspace", key: targetWorkspaceKey, position: dropPositionFromEvent(event) });', app_source)
        self.assertIn('setSidebarDropIndicator({ kind: "session", key: targetSessionId, position: dropPositionFromEvent(event) });', app_source)
        self.assertIn("const workspaceAlreadyOpen = previousSessions.some(", app_source)
        self.assertIn("if (!workspaceAlreadyOpen) setWorkspaceOrder((current) => prependOrderedKey(current, workspaceKey));", app_source)
        self.assertIn("setWorkspaceOrder((current) => prependOrderedKey(current, workspaceKey));", app_source)
        self.assertIn("[workspaceKey]: appendOrderedKey(", app_source)
        self.assertIn("session.session_id,\n      ),", app_source)
        self.assertIn("writeLocalStorage(SIDEBAR_WORKSPACE_ORDER_KEY, JSON.stringify(workspaceOrder));", app_source)
        self.assertIn("writeLocalStorage(SIDEBAR_SESSION_ORDER_KEY, JSON.stringify(sessionOrderByWorkspace));", app_source)
        self.assertIn("draggable\n                  onDragStart={(event) => handleWorkspaceDragStart(event, group.key)}", app_source)
        self.assertIn("onDragOver={(event) => handleWorkspaceDragOver(event, group.key)}", app_source)
        self.assertIn("onDragStart={(event) => handleSessionDragStart(event, group.key, session.session_id)}", app_source)
        self.assertIn("onDragOver={(event) => handleSessionDragOver(event, group.key, session.session_id)}", app_source)
        self.assertIn('.workspaceGroup[draggable="true"],\n.workspace[draggable="true"] {\n  cursor: grab;', css_source)
        self.assertIn(".workspaceGroup.is-dragging,\n.workspace.is-dragging {\n  opacity: 0.52;\n  transform: scale(0.985);", css_source)
        self.assertIn(".workspaceGroup.is-drop-before::before,\n.workspaceGroup.is-drop-after::after,", css_source)
        self.assertIn(".workspaceGroup.is-drop-before .workspaceGroupHeader,\n.workspaceGroup.is-drop-after .workspaceGroupHeader {", css_source)
        self.assertIn(".workspace.is-drop-before,\n.workspace.is-drop-after {\n  border-color: rgba(37, 99, 235, 0.34);", css_source)

    def test_sidebar_session_context_menu_exposes_session_actions(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        api_source = API_TS.read_text(encoding="utf-8")
        types_source = TYPES_TS.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn("export type EditSessionResponse = {", types_source)
        self.assertIn("editSession(", api_source)
        self.assertIn('`/api/sessions/${encodeURIComponent(sessionId)}/edit`', api_source)
        self.assertIn('const [sessionMarkerBusyId, setSessionMarkerBusyId] = useState("");', app_source)
        self.assertIn('const IMPORTANT_PRIORITY_OFFSET = 0.85;', app_source)
        self.assertIn('type SessionMarkerState = "default" | "important";', app_source)
        self.assertIn("function sessionIsImportant(session: SessionSummary | null)", app_source)
        self.assertIn("function sessionMarkerState(session: SessionSummary | null): SessionMarkerState", app_source)
        self.assertIn("async function handleSessionMarker(session: SessionSummary, nextState: SessionMarkerState)", app_source)
        self.assertIn("await api.editSession(session.session_id, {", app_source)
        self.assertIn('name: String(session.alias || ""),', app_source)
        self.assertIn('const priorityOffset = nextState === "important" ? IMPORTANT_PRIORITY_OFFSET : 0;', app_source)
        self.assertIn('const currentWorkspace = groupedSessions.find((group) => group.key === workspaceKey) || null;', app_source)
        self.assertIn('setWorkspaceOrder((current) => insertOrderedKeyAfterAnchors(current, workspaceKey, starredWorkspaceKeys));', app_source)
        self.assertIn('const nextWorkspaceKeys = uniqueStringsInOrder(nextSessions.map((item) => workspaceKeyForSession(item)));', app_source)
        self.assertIn('const nextImportantWorkspaceKeySet = new Set(', app_source)
        self.assertIn('return partitionImportantFirst(normalized, (key) => nextImportantWorkspaceKeySet.has(key));', app_source)
        self.assertIn('[workspaceKey]: insertOrderedKeyAfterAnchors(', app_source)
        self.assertIn('pushToast(nextState === "important" ? "Starred session" : "Session star cleared");', app_source)
        self.assertIn("type SidebarContextMenuEvent = JSX.TargetedMouseEvent<HTMLElement>;", app_source)
        self.assertIn("const [sessionContextMenu, setSessionContextMenu] = useState<{ sessionId: string; x: number; y: number } | null>(null);", app_source)
        self.assertIn("const contextMenuSession = useMemo(", app_source)
        self.assertIn("function openSessionContextMenu(event: SidebarContextMenuEvent, session: SessionSummary)", app_source)
        self.assertIn("setSessionContextMenu({ sessionId: session.session_id, x: event.clientX, y: event.clientY });", app_source)
        self.assertIn("function focusSidebarSession(sessionId: string)", app_source)
        self.assertIn("onContextMenu={(event) => openSessionContextMenu(event, session)}", app_source)
        self.assertIn('className="sessionContextMenu"', app_source)
        self.assertIn('Star session', app_source)
        self.assertIn('Clear star', app_source)
        self.assertNotIn('Mark ignore for now', app_source)
        self.assertIn("openRenameDialog(contextMenuSession)", app_source)
        self.assertIn("setShowDetailsPanel(true);", app_source)
        self.assertIn("setShowFilesPanel(true);", app_source)
        self.assertIn("void handleInterrupt(contextMenuSession)", app_source)
        self.assertIn("copyToClipboard(tmuxAttachCommandForSession(contextMenuSession))", app_source)
        self.assertIn("void handleCloseSession(contextMenuSession)", app_source)
        self.assertIn(".sessionContextMenu {\n  position: fixed;", css_source)
        self.assertIn(".sessionContextMenu .dangerText {\n  color: var(--danger);", css_source)

    def test_sidebar_session_cards_have_marker_buttons(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn('const markerState = sessionMarkerState(session);', app_source)
        self.assertIn('const importantMarked = markerState === "important";', app_source)
        self.assertIn('const markerBusy = sessionMarkerBusyId === session.session_id;', app_source)
        self.assertIn('className={`workspace${selectedSessionId === session.session_id ? " active" : ""}', app_source)
        self.assertIn('importantMarked ? " is-important" : ""', app_source)
        self.assertIn('className="workspaceSelect"', app_source)
        self.assertIn('className="workspaceMarkers"', app_source)
        self.assertIn('className={`workspaceMarkerBtn${importantMarked ? " active" : ""}`}', app_source)
        self.assertIn('title={importantMarked ? "Clear star" : "Star session"}', app_source)
        self.assertIn('void handleSessionMarker(session, importantMarked ? "default" : "important")', app_source)
        self.assertIn('case "star":', app_source)
        self.assertNotIn('case "later":', app_source)
        self.assertIn('.workspace.is-important {', css_source)
        self.assertNotIn('.workspace.is-muted:not(.active) {', css_source)
        self.assertIn('.workspaceSelect {', css_source)
        self.assertIn('.workspaceHeader {\n  display: grid;\n  gap: 4px;\n  min-width: 0;\n  padding-right: 48px;\n}', css_source)
        self.assertIn('.workspaceMarkers {', css_source)
        self.assertIn('.workspaceMarkerBtn {', css_source)
        self.assertIn('.workspaceMarkerBtn.active {', css_source)
        self.assertIn('border-color: transparent;', css_source)
        self.assertIn('background: transparent;', css_source)
        self.assertIn('box-shadow: none;', css_source)
        self.assertNotIn('.workspaceMarkerBtn-muted.active {', css_source)

    def test_tool_events_default_to_collapsed(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        transcript_source = TRANSCRIPT_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn("function isCollapsibleEvent(kind: UiTranscriptEvent[\"kind\"])", transcript_source)
        self.assertIn("function compactPreviewText(text: string)", transcript_source)
        self.assertIn("function unwrapToolResultEnvelope(text: string)", transcript_source)
        self.assertIn("function applyPatchPreview(event: UiTranscriptEvent)", transcript_source)
        self.assertIn("function writeStdinPreview(event: UiTranscriptEvent)", transcript_source)
        self.assertIn("function toolSpecificPreview(event: UiTranscriptEvent)", transcript_source)
        self.assertIn('if (toolName === "apply_patch") return applyPatchPreview(event);', transcript_source)
        self.assertIn('if (toolName === "write_stdin") return writeStdinPreview(event);', transcript_source)
        self.assertIn('return `Updated ${files.length} files: ${preview}${files.length > 3 ? ", ..." : ""}`;', transcript_source)
        self.assertIn('return Number(exitMatch[1]) === 0 ? "No new terminal output" : `Exited with code ${exitMatch[1]}`;', transcript_source)
        self.assertIn('find((entry) => entry && !/^Total output lines: \\d+$/i.test(entry));', transcript_source)
        self.assertIn("const specialized = toolSpecificPreview(event);", transcript_source)
        self.assertIn("if (specialized) return specialized;", transcript_source)
        self.assertIn("function stripRepeatedTitlePrefix(preview: string, title: string)", transcript_source)
        self.assertIn('const body = String((event.kind === "tool" && event.toolCallBody) || event.body || event.toolResultBody || "").trim();', transcript_source)
        self.assertIn("return stripRepeatedTitlePrefix(preview, event.title);", transcript_source)
        self.assertIn("const knownToolTitles = new Map<string, string>();", transcript_source)
        self.assertIn('event.type !== "tool" || !event.tool_call_id', transcript_source)
        self.assertIn("knownToolTitles.set(event.tool_call_id, event.name.trim());", transcript_source)
        self.assertIn("function toolEventMeta(toolCallId: string, isError: boolean)", transcript_source)
        self.assertIn("function mergeToolCallAndResult(toolCall: UiTranscriptEvent, toolResult: UiTranscriptEvent): UiTranscriptEvent", transcript_source)
        self.assertIn("function mergeToolPair(existing: UiTranscriptEvent, incoming: UiTranscriptEvent)", transcript_source)
        self.assertIn("function collapseToolResultPairs(events: UiTranscriptEvent[])", transcript_source)
        self.assertIn('const toolTitle = raw.type === "tool_result" ? knownName || (rawName === "tool" ? "" : rawName) : rawName;', transcript_source)
        self.assertIn('title: toolTitle || (raw.type === "tool_result" ? "Tool result" : "Tool call")', transcript_source)
        self.assertIn('toolCallBody: raw.type === "tool" ? String(raw.text || "") : undefined,', transcript_source)
        self.assertIn('toolResultBody: raw.type === "tool_result" ? String(raw.text || "") : undefined,', transcript_source)
        self.assertIn("return collapseToolResultPairs(out);", transcript_source)
        self.assertIn("function transcriptEventCollapsed(event: UiTranscriptEvent, collapsedState = collapsedEvents)", app_source)
        self.assertIn("return askUserDefaultsOpen(event) ? collapsedState[event.id] === true : collapsedState[event.id] !== false;", app_source)
        self.assertIn("setCollapsedEvents((current) => ({ ...current, [event.id]: !transcriptEventCollapsed(event, current) }));", app_source)
        self.assertIn("setCollapsedEvents({});", app_source)
        self.assertIn("const collapsed = transcriptEventCollapsed(event);", app_source)
        self.assertIn("setTranscript((current) => mergeTranscriptEvents(older, current));", app_source)
        self.assertIn('className={`message-side${showMessageSide && !collapsible ? "" : " is-hidden"}`}', transcript_source)
        self.assertIn("showMessageSide && !collapsible ? ", transcript_source)
        self.assertIn('<div className="message-inline">', transcript_source)
        self.assertIn('<span className="message-fold" aria-label="Show details" title="Show details" />', transcript_source)
        self.assertIn("function ToolEventDetails(props: { event: UiTranscriptEvent })", transcript_source)
        self.assertIn('<div className="tool-pair">', transcript_source)
        self.assertIn('<div className="tool-part-label">Call</div>', transcript_source)
        self.assertIn('<div className="tool-part-label">Result</div>', transcript_source)
        self.assertIn('event.kind === "tool" ? <ToolEventDetails event={event} /> : null', transcript_source)
        self.assertNotIn("message-time-end", transcript_source)
        self.assertIn('<div className="message-inline is-open">', transcript_source)
        self.assertIn('<span className="message-fold is-open" aria-label="Hide details" title="Hide details" />', transcript_source)
        self.assertNotIn('{">"}</span>', transcript_source)
        self.assertNotIn('<span className="message-fold">Expand</span>', transcript_source)
        self.assertNotIn('<span className="message-fold">Collapse</span>', transcript_source)
        self.assertIn(".msg {\n  width: 100%;\n  display: grid;", css_source)
        self.assertIn("border-top: 0;\n  overflow-wrap: anywhere;", css_source)
        self.assertIn(".event-user + .event-assistant,\n.event-assistant + .event-user {\n  border-top: 1px solid rgba(15, 23, 42, 0.08);", css_source)
        self.assertIn(".event-tool,\n.event-result,\n.event-question {\n  padding: 8px 0;", css_source)
        self.assertNotIn(".event-tool + .event-tool", css_source)
        self.assertIn(".event-tool.is-collapsed,\n.event-result.is-collapsed,\n.event-question.is-collapsed {\n  align-items: center;\n  padding: 4px 0;", css_source)
        self.assertIn(".event-tool .message-main,\n.event-result .message-main,\n.event-question .message-main {\n  padding: 6px 0;\n  border-left: 0;\n  background: transparent;", css_source)
        self.assertIn(".event-tool .message-kind,\n.event-result .message-kind,\n.event-question .message-kind {\n  background: transparent;", css_source)
        self.assertIn(".is-collapsible:hover .message-main {\n  background: transparent;", css_source)
        self.assertIn(".is-collapsible {\n  cursor: pointer;\n}", css_source)
        self.assertIn(".tool-pair {\n  display: grid;\n  gap: 10px;\n  width: 100%;\n  max-width: 760px;\n  padding-left: 12px;\n  box-sizing: border-box;\n  justify-items: start;", css_source)
        self.assertIn(".tool-part {\n  display: grid;\n  gap: 6px;\n  width: 100%;\n  justify-items: start;", css_source)
        self.assertIn(".tool-part-label {\n  font-size: 11px;", css_source)
        self.assertIn(".tool-part .message-body {\n  width: 100%;\n}", css_source)
        self.assertNotIn("grid-template-columns: 64px minmax(0, 1fr);", css_source)
        self.assertIn(".event-question .message-main {\n  background: transparent;", css_source)
        self.assertIn(".is-collapsed .message-side {\n  display: none;", css_source)
        self.assertIn(".is-collapsible .message-side {\n  visibility: hidden;", css_source)
        self.assertIn(".is-collapsible .message-main,\n.is-collapsed .message-main {\n  grid-column: 2;\n  border-left: 0;", css_source)
        self.assertIn(".is-collapsed .message-main {\n  padding: 2px 0;", css_source)
        self.assertIn(".message-inline {\n  display: flex;", css_source)
        self.assertIn(".message-inline .message-fold {\n  position: relative;\n  width: 16px;\n  min-height: 16px;\n  padding: 0;\n  border: 0;\n  background: transparent;", css_source)
        self.assertNotIn("background: rgba(11, 15, 20, 0.52);", css_source)
        self.assertNotIn("background: rgba(255, 255, 255, 0.72);", css_source)
        self.assertIn(":root[data-theme=\"light\"] .event-tool .message-kind,\n:root[data-theme=\"light\"] .event-result .message-kind,\n:root[data-theme=\"light\"] .event-question .message-kind {\n  background: transparent;", css_source)
        self.assertIn('.message-inline .message-fold::before {\n  content: "";', css_source)
        self.assertIn("border-right: 1.5px solid currentColor;\n  border-bottom: 1.5px solid currentColor;", css_source)
        self.assertIn(".message-inline .message-fold.is-open::before {\n  top: 6px;\n  transform: rotate(225deg);", css_source)
        self.assertIn(".message-inline.is-open {\n  margin-bottom: 6px;", css_source)
        self.assertIn(".message-inline .message-summary {\n  min-width: 0;\n  flex: 1 1 auto;", css_source)
        self.assertIn(".message-summary {\n  overflow: hidden;", css_source)

    def test_ask_user_rows_can_be_answered_from_transcript(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        transcript_source = TRANSCRIPT_TSX.read_text(encoding="utf-8")
        types_source = TYPES_TS.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn("export type UiAskUserQuestion = {", types_source)
        self.assertIn("askOptions?: AskUserOption[];", types_source)
        self.assertIn("askQuestions?: UiAskUserQuestion[];", types_source)
        self.assertIn("function AskUserPrompt(props: {", transcript_source)
        self.assertIn("function answerTextForAskUser(event: UiTranscriptEvent, values: string[], freeform: string, bridgeAnswers: Record<string, string | string[]>)", transcript_source)
        self.assertIn("void submit([value], \"\");", transcript_source)
        self.assertIn('placeholder="Type an answer"', transcript_source)
        self.assertIn('event.kind === "ask_user" ? <AskUserPrompt event={event} onRespond={onAskUserRespond} /> : null', transcript_source)
        self.assertIn("async function handleAskUserRespond(event: UiTranscriptEvent, text: string)", app_source)
        self.assertIn("await api.sendMessage(sessionId, text);", app_source)
        self.assertIn("onAskUserRespond={handleAskUserRespond}", app_source)
        self.assertIn("function askUserDefaultsOpen(event: UiTranscriptEvent)", app_source)
        self.assertIn(".ask-user-options {\n  display: flex;", css_source)
        self.assertIn(".ask-user-option.is-selected", css_source)
        self.assertIn(".ask-user-composer {\n  display: grid;", css_source)

    def test_extension_progress_events_render_as_structured_transcript_rows(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        transcript_source = TRANSCRIPT_TSX.read_text(encoding="utf-8")
        types_source = TYPES_TS.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn('type: "extension";', types_source)
        self.assertIn('kind: "user" | "assistant" | "tool" | "tool_result" | "ask_user" | "extension";', types_source)
        self.assertIn("toolCallBody?: string;", types_source)
        self.assertIn("toolResultBody?: string;", types_source)
        self.assertIn('if (raw.type === "extension")', transcript_source)
        self.assertIn('function isTodoExtensionEvent(raw: Extract<RawChatEvent, { type: "extension" }>)', transcript_source)
        self.assertIn('kind: isTodoExtensionEvent(raw) ? "tool" : "extension"', transcript_source)
        self.assertIn('body: isTodoExtensionEvent(raw) ? String(summary || raw.text || "") : String(raw.text || "")', transcript_source)
        self.assertIn("function ExtensionProgress(props: { event: UiTranscriptEvent })", transcript_source)
        self.assertIn('<div className="extension-progress"', transcript_source)
        self.assertIn('<ol className="extension-items">', transcript_source)
        self.assertIn('case "extension":\n      return "event-extension";', transcript_source)
        self.assertIn('event.kind === "user" || event.kind === "assistant" || event.kind === "extension"', app_source)
        self.assertIn("function isFloatingProgressEvent(event: UiTranscriptEvent)", app_source)
        self.assertIn('if (event.extensionKind !== "progress") return false;', app_source)
        self.assertNotIn('if (event.kind !== "extension") return false;', app_source)
        self.assertIn('return title === "todo" || title === "ralph loop" || source === "codex" || source === "ralph-loop";', app_source)
        self.assertIn("function isFloatingTodoProgressEvent(event: UiTranscriptEvent)", app_source)
        self.assertIn('return title === "todo" || source === "codex";', app_source)
        self.assertIn("function FloatingProgress(props: { event: UiTranscriptEvent; collapsed: boolean; onToggle: () => void })", app_source)
        self.assertIn('const hasProgress = !isFloatingTodoProgressEvent(event) && typeof total === "number" && total > 0 && typeof current === "number";', app_source)
        self.assertIn('const title = event.title.trim() || "Progress";', app_source)
        self.assertIn('const [collapsedFloatingProgressEvents, setCollapsedFloatingProgressEvents] = useState<Record<string, boolean>>({});', app_source)
        self.assertIn("const floatingProgressEvent = useMemo(() => {", app_source)
        self.assertIn('return event.status === "completed" ? null : event;', app_source)
        self.assertIn('const floatingProgressCollapsed = Boolean(floatingProgressEvent && collapsedFloatingProgressEvents[floatingProgressEvent.id]);', app_source)
        self.assertIn('function toggleFloatingProgress(eventId: string)', app_source)
        self.assertIn('<div className={`workspaceBody${floatingProgressEvent ? " hasFloatingProgress" : ""}`}>', app_source)
        self.assertIn('<div className="workspaceMain">', app_source)
        self.assertIn('{floatingProgressEvent ? <FloatingProgress event={floatingProgressEvent} collapsed={floatingProgressCollapsed} onToggle={() => toggleFloatingProgress(floatingProgressEvent.id)} /> : null}', app_source)
        self.assertIn('<div className="composer">', app_source)
        self.assertNotIn('<div className={`composer${floatingProgressEvent ? " hasFloatingProgress" : ""}`}>', app_source)
        self.assertIn(".extension-progress-bar", css_source)
        self.assertIn(".extension-item.is-in-progress .extension-item-mark", css_source)
        self.assertIn(".workspaceMain {\n  display: flex;", css_source)
        self.assertIn(".workspaceBody.hasFloatingProgress .workspaceMain {\n  gap: 10px;", css_source)
        self.assertIn(".workspaceBody.hasFloatingProgress .chat {\n  padding-bottom: 24px;", css_source)
        self.assertIn("--floating-progress-bg: rgba(16, 21, 29, 0.94);", css_source)
        self.assertIn("--floating-progress-bg: rgba(248, 250, 252, 0.96);", css_source)
        self.assertIn(".floatingProgress {\n  flex: 0 0 auto;", css_source)
        self.assertIn('.floatingProgressHead {\n  min-width: 0;', css_source)
        self.assertIn('.floatingProgressToggle {\n  flex: 0 0 auto;', css_source)
        self.assertIn('.floatingProgress.is-collapsed {\n  gap: 0;', css_source)
        self.assertIn("border: 1px solid var(--floating-progress-border);", css_source)
        self.assertIn("background: var(--floating-progress-bg);", css_source)
        self.assertIn("margin: 0 auto 10px;", css_source)
        self.assertNotIn(".floatingProgress {\n  position: absolute;", css_source)
        self.assertNotIn("bottom: calc(100% + 10px);", css_source)
        self.assertIn('className={`floatingProgress${collapsed ? " is-collapsed" : ""}`}', app_source)
        self.assertIn('className="floatingProgressToggle"', app_source)
        self.assertIn('title={collapsed ? "Expand progress" : "Collapse progress"}', app_source)
        self.assertIn('{icon(collapsed ? "down" : "up")}', app_source)
        self.assertIn('<span>{collapsed ? "Expand" : "Collapse"}</span>', app_source)
        self.assertIn('className="floatingProgressItemLabel"', app_source)
        self.assertIn(".floatingProgressItemLabel {\n  min-width: 0;", css_source)
        self.assertIn("color: var(--floating-progress-item-color);", css_source)
        self.assertIn(".floatingProgressItem.is-completed .floatingProgressItemLabel {\n  text-decoration: line-through;", css_source)
        self.assertIn(".floatingProgressBar span {\n  display: block;", css_source)

    def test_assistant_messages_are_coalesced_and_not_background_filled(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        transcript_source = TRANSCRIPT_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn("function coalesceAdjacentAssistantEvents(events: UiTranscriptEvent[])", transcript_source)
        self.assertIn("function shouldShowMessageSide(events: UiTranscriptEvent[], index: number)", transcript_source)
        self.assertIn("meta: String(raw.message_class || \"\"),", transcript_source)
        self.assertNotIn("raw.notification_text === \"string\" && raw.notification_text.trim() ? raw.notification_text", transcript_source)
        self.assertIn("function isAssistantNarration(event: UiTranscriptEvent)", transcript_source)
        self.assertIn('return event.kind === "assistant" && event.meta.trim() === "narration";', transcript_source)
        self.assertIn("function shouldShowMessageFooter(events: UiTranscriptEvent[], index: number, collapsible: boolean)", transcript_source)
        self.assertIn("if (!event || collapsible || (!event.meta && !event.ts)) return false;", transcript_source)
        self.assertIn("if (!isAssistantNarration(event)) return true;", transcript_source)
        self.assertIn('if (next.kind === "user") return true;', transcript_source)
        self.assertIn("if (isAssistantNarration(next)) return false;", transcript_source)
        self.assertIn('second: "2-digit"', transcript_source)
        self.assertIn('previous.kind === "assistant" && event.kind === "assistant"', transcript_source)
        self.assertIn('if (previous.kind === "user") return true;', transcript_source)
        self.assertIn('if (previous.kind === "assistant") return false;', transcript_source)
        self.assertIn("function joinAssistantBodies(left: string, right: string)", transcript_source)
        self.assertIn("body: joinAssistantBodies(previous.body, event.body)", transcript_source)
        self.assertNotIn('body: [previous.body, event.body].filter((value) => value.trim()).join("\\n\\n")', transcript_source)
        self.assertIn("return out;", transcript_source)
        self.assertIn("const existingIndex = next.findIndex((currentEvent) => currentEvent.id === event.id);", transcript_source)
        self.assertIn("const merged = mergeToolPair(next[existingIndex], event);", transcript_source)
        self.assertIn("next[existingIndex] = merged || event;", transcript_source)
        self.assertIn("() =>\n      coalesceAdjacentAssistantEvents(", app_source)
        self.assertIn('event.kind === "user" || event.kind === "assistant" || event.kind === "extension"', app_source)
        self.assertIn("const showMessageSide = shouldShowMessageSide(events, index);", transcript_source)
        self.assertIn("const showMessageFooter = shouldShowMessageFooter(events, index, collapsible);", transcript_source)
        self.assertIn('className={`message-side${showMessageSide && !collapsible ? "" : " is-hidden"}`}', transcript_source)
        self.assertIn('<div className="message-footer">', transcript_source)
        self.assertIn("{collapsible && event.meta ? <div className=\"message-meta\">{event.meta}</div> : null}", transcript_source)
        self.assertIn("showMessageFooter ? (", transcript_source)
        self.assertIn('{event.meta ? <span className="message-meta">{event.meta}</span> : null}', transcript_source)
        self.assertIn('<span className="message-time">{formatTime(event.ts)}</span>', transcript_source)
        self.assertIn(".event-user .message-main,\n.event-assistant .message-main {\n  padding: 2px 0;\n  border-left: 0;", css_source)
        self.assertIn(".event-user .message-main {\n  border-radius: 8px;\n  background: rgba(37, 99, 235, 0.06);", css_source)
        self.assertIn(".msg {\n  width: 100%;\n  display: grid;\n  grid-template-columns: 118px minmax(0, 1fr) 118px;", css_source)
        self.assertIn(".event-user .message-side {\n  grid-column: 3;\n  align-items: flex-end;\n  text-align: right;", css_source)
        self.assertIn(".event-user .message-main {\n  grid-column: 2;\n  grid-row: 1;", css_source)
        self.assertIn(".event-user .message-side {\n    grid-column: 1;\n    grid-row: 1;\n    justify-content: flex-end;", css_source)
        self.assertIn(".event-user .message-main {\n    grid-column: 1;\n    grid-row: 2;", css_source)
        self.assertNotIn("border-left-color: rgba(37, 99, 235, 0.32);", css_source)
        self.assertIn(".event-assistant .message-main {\n  border-left: 0;\n  background: transparent;\n  padding: 2px 0;", css_source)
        self.assertIn(".status-chip {\n  background: rgba(15, 23, 42, 0.08);", css_source)
        self.assertNotIn(".status-chip,\n.message-kind {\n  background:", css_source)
        self.assertIn(":root[data-theme=\"light\"] .event-user .message-kind {\n  color: #1d4ed8;\n  background: transparent;", css_source)
        self.assertIn(":root[data-theme=\"light\"] .event-assistant .message-kind {\n  color: #0f172a;\n  background: transparent;", css_source)
        self.assertIn(".message-footer {\n  display: flex;\n  align-items: baseline;\n  justify-content: flex-start;\n  gap: 8px;\n  margin-top: 8px;", css_source)
        self.assertNotIn(".message-time-end", css_source)
        self.assertIn(".message-side.is-hidden {\n  visibility: hidden;", css_source)

    def test_composer_layout_is_pinned_outside_scroll_region(self) -> None:
        source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn(".main {\n  display: flex;\n  flex-direction: column;", source)
        self.assertIn(".workspaceBody {\n  flex: 1 1 auto;", source)
        self.assertIn("  overflow: hidden;\n}\n\n.detailRail", source)
        self.assertIn(".chatWrap {\n  display: flex;", source)
        self.assertIn(".chat {\n  flex: 1 1 auto;", source)
        self.assertIn(".composer {\n  position: sticky;\n  bottom: 0;", source)
        self.assertIn("grid-template-rows: minmax(0, 1fr) minmax(160px, 38vh);", source)
        self.assertIn(".composerMode {\n  display: inline-flex;", source)
        self.assertIn(".modeBtn.active {\n  background: var(--accent-soft);", source)
        self.assertIn(".inputWrap textarea {\n  display: block;", source)
        self.assertIn("line-height: 1.4;", source)
        self.assertIn(".ph {\n  position: absolute;\n  inset: 0;\n  padding: 10px 12px;", source)
        self.assertIn("font: inherit;", source)

    def test_transcript_autoscroll_respects_history_browsing(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("const CHAT_BOTTOM_FOLLOW_THRESHOLD_PX = 96;", source)
        self.assertIn("function isNearScrollBottom(element: HTMLElement)", source)
        self.assertIn("element.scrollHeight - element.scrollTop - element.clientHeight <= CHAT_BOTTOM_FOLLOW_THRESHOLD_PX", source)
        self.assertIn("const chatScrollRef = useRef<HTMLDivElement | null>(null);", source)
        self.assertIn("const stickToBottomRef = useRef(true);", source)
        self.assertIn("const lastAutoScrollKeyRef = useRef(\"\");", source)
        self.assertIn("function updateChatScrollFollowState()", source)
        self.assertIn("stickToBottomRef.current = isNearScrollBottom(element);", source)
        self.assertIn("if ((!visibleTranscript.length && !workingIndicatorLabel) || !stickToBottomRef.current) return;", source)
        self.assertIn("window.requestAnimationFrame(() => {", source)
        self.assertIn("element.scrollTop = element.scrollHeight;", source)
        self.assertIn('<div className="chat" ref={chatScrollRef} onScroll={updateChatScrollFollowState}>', source)


if __name__ == "__main__":
    unittest.main()
