import pathlib
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]
APP_TSX = ROOT / "frontend" / "src" / "app.tsx"
API_TS = ROOT / "frontend" / "src" / "lib" / "api.ts"
STYLES_CSS = ROOT / "frontend" / "src" / "styles.css"


class NovaPreviewSourceTest(unittest.TestCase):
    def test_new_session_defaults_to_tmux_when_available(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("setNewSessionTmux(tmuxAvailable);", source)
        self.assertIn("create_in_tmux: tmuxAvailable && newSessionTmux", source)

    def test_new_session_selection_updates_ref_before_send(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("function selectSession(sessionId: string) {", source)
        self.assertIn("selectedSessionRef.current = sessionId;", source)
        self.assertIn("selectSession(found.session_id);", source)

    def test_new_session_dialog_closes_before_background_follow(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("const composerInputRef = useRef<HTMLTextAreaElement | null>(null);", source)
        self.assertIn("function focusComposerInput()", source)
        self.assertIn("async function followCreatedSession(brokerPid: number)", source)
        self.assertIn("setNewSessionOpen(false);\n      void followCreatedSession(result.broker_pid)", source)
        self.assertIn("ref={composerInputRef}", source)

    def test_rename_session_control_is_wired_to_api(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        api_source = API_TS.read_text(encoding="utf-8")
        self.assertIn("renameSession(sessionId: string, name: string)", api_source)
        self.assertIn("/rename", api_source)
        self.assertIn("function openRenameDialog()", app_source)
        self.assertIn("void handleRenameSession()", app_source)
        self.assertIn('className="icon-btn"', app_source)
        self.assertIn('{icon("edit")}', app_source)
        self.assertNotIn("<span>Rename</span>", app_source)
        self.assertIn('title={selectedSession ? "Rename session" : "No session selected"}', app_source)

    def test_send_has_visible_pending_state_and_busy_queue_path(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("const [sending, setSending] = useState(false);", source)
        self.assertIn("function mergeTranscriptEvents(current: UiTranscriptEvent[], incoming: UiTranscriptEvent[])", source)
        self.assertIn("let localEvent: UiTranscriptEvent | null = null;", source)
        self.assertIn("if (!shouldQueue) {\n      localEvent = {", source)
        self.assertIn('id: `local-user-${Date.now()}`', source)
        self.assertIn('meta: "sending"', source)
        self.assertNotIn('meta: shouldQueue ? "queued" : "sending"', source)
        self.assertIn("const shouldQueue = Boolean(busy || selectedSession?.busy);", source)
        self.assertIn("await api.enqueueMessage(sessionId, text);", source)
        self.assertNotIn("meta: `queued${response.queue_len", source)
        self.assertIn("await api.sendMessage(sessionId, text);", source)
        self.assertIn('title={sending ? "Sending…" : "Send"}', source)
        self.assertIn("disabled={sending || !selectedSessionId}", source)

    def test_close_session_control_uses_delete_api(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        api_source = API_TS.read_text(encoding="utf-8")
        self.assertIn("deleteSession(sessionId: string)", api_source)
        self.assertIn("/delete", api_source)
        self.assertIn("async function handleCloseSession()", app_source)
        self.assertIn("await api.deleteSession(sessionId);", app_source)
        self.assertIn('title={selectedSession ? "Close session" : "No session selected"}', app_source)
        self.assertIn('className="icon-btn danger"', app_source)

    def test_tmux_copy_handles_missing_clipboard_api(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("function copyTextViaSelection(text: string)", source)
        self.assertIn('typeof document.execCommand !== "function"', source)
        self.assertIn('document.execCommand("copy")', source)
        self.assertIn("async function copyToClipboard(text: string)", source)
        self.assertIn("navigator.clipboard && typeof navigator.clipboard.writeText === \"function\"", source)
        self.assertIn("await copyToClipboard(tmuxCommand);", source)
        self.assertNotIn("await navigator.clipboard.writeText(tmuxCommand);", source)
        self.assertIn('title={tmuxCommand || "No tmux attach command for this session"}', source)
        self.assertIn('{icon("terminal")}', source)
        self.assertEqual(source.count('{icon("tmux")}'), 0)

    def test_topbar_tool_toggle_uses_wrench_icon(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn('case "wrench":', source)
        self.assertIn('title={showTools ? "Hide tool calls" : "Show tool calls"}', source)
        self.assertIn('{icon("wrench")}', source)
        self.assertIn("The wrench button toggles tool, tool result, and ask-user events", source)

    def test_topbar_uses_stable_session_status_not_polling_label(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("const topSessionStatus = useMemo(() => {", source)
        self.assertIn('if (queueLen) return `queue ${queueLen}`;', source)
        self.assertIn('if (awaitingAssistantReply || busy || selectedSession.busy) return "working";', source)
        self.assertIn('if (sessionIsStarting(selectedSession)) return "starting";', source)
        self.assertIn('const topSessionStatusClass = topSessionStatus === "working" || topSessionStatus === "starting" ? "status-chip working" : "status-chip";', source)
        self.assertIn('<span className={topSessionStatusClass}>{topSessionStatus}</span>', source)
        self.assertNotIn("connectionLabel", source)
        self.assertNotIn("loading transcript", source)

    def test_new_session_working_status_marks_startup_and_awaiting_reply(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn("function sessionIsStarting(session: SessionSummary | null)", app_source)
        self.assertIn('if (sessionIsStarting(session)) return "starting";', app_source)
        self.assertIn("const awaitingAssistantReply = useMemo(() => {", app_source)
        self.assertIn("return latestUserTs > latestAssistantTs;", app_source)
        self.assertIn("session.busy || sessionIsStarting(session) ? \"running\" : \"idle\"", app_source)
        self.assertIn(".status-chip.working", css_source)

    def test_sidebar_preview_uses_latest_user_message(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("function previewFromEvents(events: UiTranscriptEvent[])", source)
        self.assertIn('if (event.kind !== "user") continue;', source)
        self.assertNotIn('if (event.kind !== "user" && event.kind !== "assistant") continue;', source)
        self.assertIn("setSessionLastLines((current) => ({ ...current, [sessionId]: previewFromEvents(nextEvents) || current[sessionId] || \"\" }));", source)
        self.assertIn("setSessionLastLines((prev) => ({ ...prev, [sessionId]: previewFromEvents(merged) || prev[sessionId] || \"\" }));", source)

    def test_tool_events_default_to_collapsed(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn("function isCollapsibleEvent(kind: UiTranscriptEvent[\"kind\"])", app_source)
        self.assertIn("function stripRepeatedTitlePrefix(preview: string, title: string)", app_source)
        self.assertIn("return stripRepeatedTitlePrefix(preview, event.title);", app_source)
        self.assertIn("const knownToolTitles = new Map<string, string>();", app_source)
        self.assertIn('event.type !== "tool" || !event.tool_call_id', app_source)
        self.assertIn("knownToolTitles.set(event.tool_call_id, event.name.trim());", app_source)
        self.assertIn('const toolTitle = raw.type === "tool_result" ? knownName || (rawName === "tool" ? "" : rawName) : rawName;', app_source)
        self.assertIn('title: toolTitle || (raw.type === "tool_result" ? "Tool result" : "Tool call")', app_source)
        self.assertIn("setCollapsedEvents((current) => ({ ...current, [eventId]: current[eventId] === false }));", app_source)
        self.assertIn("setCollapsedEvents({});", app_source)
        self.assertIn("const collapsed = Boolean(collapsible && collapsedEvents[event.id] !== false);", app_source)
        self.assertIn('className={`message-side${showMessageSide && !collapsible ? "" : " is-hidden"}`}', app_source)
        self.assertIn("showMessageSide && !collapsible ? (", app_source)
        self.assertIn('<div className="message-inline">', app_source)
        self.assertIn('<span className="message-fold" aria-label="Show details" title="Show details" />', app_source)
        self.assertNotIn("message-time-end", app_source)
        self.assertIn('<div className="message-inline is-open">', app_source)
        self.assertIn('<span className="message-fold is-open" aria-label="Hide details" title="Hide details" />', app_source)
        self.assertNotIn('{">"}</span>', app_source)
        self.assertNotIn('<span className="message-fold">Expand</span>', app_source)
        self.assertNotIn('<span className="message-fold">Collapse</span>', app_source)
        self.assertIn(".event-tool .message-main,\n.event-result .message-main,\n.event-question .message-main {\n  padding: 12px 0;\n  border-left: 0;\n  background: transparent;", css_source)
        self.assertIn(".event-tool .message-kind,\n.event-result .message-kind,\n.event-question .message-kind {\n  background: transparent;", css_source)
        self.assertIn(".is-collapsible:hover .message-main {\n  background: transparent;", css_source)
        self.assertIn(".is-collapsible {\n  cursor: pointer;\n}", css_source)
        self.assertNotIn("grid-template-columns: 64px minmax(0, 1fr);", css_source)
        self.assertIn(".event-question .message-main {\n  background: transparent;", css_source)
        self.assertIn(".is-collapsed .message-side {\n  display: none;", css_source)
        self.assertIn(".is-collapsible .message-side {\n  visibility: hidden;", css_source)
        self.assertIn(".is-collapsible .message-main,\n.is-collapsed .message-main {\n  grid-column: 2;\n  border-left: 0;", css_source)
        self.assertIn(".is-collapsed .message-main {\n  padding: 6px 0;", css_source)
        self.assertIn(".message-inline {\n  display: flex;", css_source)
        self.assertIn(".message-inline .message-fold {\n  position: relative;\n  width: 16px;\n  min-height: 16px;\n  padding: 0;\n  border: 0;\n  background: transparent;", css_source)
        self.assertIn('.message-inline .message-fold::before {\n  content: "";', css_source)
        self.assertIn("border-right: 1.5px solid currentColor;\n  border-bottom: 1.5px solid currentColor;", css_source)
        self.assertIn(".message-inline .message-fold.is-open::before {\n  top: 6px;\n  transform: rotate(225deg);", css_source)
        self.assertIn(".message-inline.is-open {\n  margin-bottom: 10px;", css_source)
        self.assertIn(".message-inline .message-summary {\n  min-width: 0;\n  flex: 1 1 auto;", css_source)
        self.assertIn(".message-summary {\n  overflow: hidden;", css_source)

    def test_assistant_messages_are_coalesced_and_not_background_filled(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn("function coalesceAdjacentAssistantEvents(events: UiTranscriptEvent[])", app_source)
        self.assertIn("function shouldShowMessageSide(events: UiTranscriptEvent[], index: number)", app_source)
        self.assertIn("meta: String(raw.message_class || \"\"),", app_source)
        self.assertNotIn("raw.notification_text === \"string\" && raw.notification_text.trim() ? raw.notification_text", app_source)
        self.assertIn("function isAssistantNarration(event: UiTranscriptEvent)", app_source)
        self.assertIn('return event.kind === "assistant" && event.meta.trim() === "narration";', app_source)
        self.assertIn("function shouldShowMessageFooter(events: UiTranscriptEvent[], index: number, collapsible: boolean)", app_source)
        self.assertIn("if (!event || collapsible || (!event.meta && !event.ts)) return false;", app_source)
        self.assertIn("if (!isAssistantNarration(event)) return true;", app_source)
        self.assertIn('if (next.kind === "user") return true;', app_source)
        self.assertIn("if (isAssistantNarration(next)) return false;", app_source)
        self.assertIn('second: "2-digit"', app_source)
        self.assertIn('previous.kind === "assistant" && event.kind === "assistant"', app_source)
        self.assertIn('if (previous.kind === "user") return true;', app_source)
        self.assertIn('if (previous.kind === "assistant") return false;', app_source)
        self.assertIn('body: [previous.body, event.body].filter((value) => value.trim()).join("\\n\\n")', app_source)
        self.assertIn("return out;", app_source)
        self.assertIn("return current\n    .filter((event) => !incomingIds.has(event.id))", app_source)
        self.assertIn("() => coalesceAdjacentAssistantEvents(showTools ? transcript", app_source)
        self.assertIn("const showMessageSide = shouldShowMessageSide(visibleTranscript, index);", app_source)
        self.assertIn("const showMessageFooter = shouldShowMessageFooter(visibleTranscript, index, collapsible);", app_source)
        self.assertIn('className={`message-side${showMessageSide && !collapsible ? "" : " is-hidden"}`}', app_source)
        self.assertIn('<div className="message-footer">', app_source)
        self.assertIn("{collapsible && event.meta ? <div className=\"message-meta\">{event.meta}</div> : null}", app_source)
        self.assertIn("showMessageFooter ? (", app_source)
        self.assertIn('{event.meta ? <span className="message-meta">{event.meta}</span> : null}', app_source)
        self.assertIn('<span className="message-time">{formatTime(event.ts)}</span>', app_source)
        self.assertIn(".event-user .message-main,\n.event-assistant .message-main {\n  padding: 2px 0;\n  border-left: 0;", css_source)
        self.assertIn(".event-user .message-main {\n  border-radius: 8px;\n  background: rgba(37, 99, 235, 0.06);", css_source)
        self.assertNotIn("border-left-color: rgba(37, 99, 235, 0.32);", css_source)
        self.assertIn(".event-assistant .message-main {\n  border-left: 0;\n  background: transparent;\n  padding: 2px 0;", css_source)
        self.assertIn(".message-footer {\n  display: flex;\n  align-items: baseline;\n  justify-content: flex-start;\n  gap: 8px;\n  margin-top: 8px;", css_source)
        self.assertNotIn(".message-time-end", css_source)
        self.assertIn(".message-side.is-hidden {\n  visibility: hidden;", css_source)

    def test_composer_layout_is_pinned_outside_scroll_region(self) -> None:
        source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn(".main {\n  display: flex;\n  flex-direction: column;", source)
        self.assertIn(".workspaceBody {\n  flex: 1 1 auto;", source)
        self.assertIn("  overflow: hidden;\n}\n\n.detailRail", source)
        self.assertIn(".chatWrap {\n  display: flex;", source)
        self.assertIn(".chat {\n  flex: 1 1 auto;", source)
        self.assertIn(".composer {\n  position: sticky;\n  bottom: 0;", source)
        self.assertIn("grid-template-rows: minmax(0, 1fr) minmax(160px, 38vh);", source)

    def test_transcript_autoscroll_respects_history_browsing(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("const CHAT_BOTTOM_FOLLOW_THRESHOLD_PX = 96;", source)
        self.assertIn("function isNearScrollBottom(element: HTMLElement)", source)
        self.assertIn("element.scrollHeight - element.scrollTop - element.clientHeight <= CHAT_BOTTOM_FOLLOW_THRESHOLD_PX", source)
        self.assertIn("const chatScrollRef = useRef<HTMLDivElement | null>(null);", source)
        self.assertIn("const stickToBottomRef = useRef(true);", source)
        self.assertIn("const lastAutoScrollKeyRef = useRef(\"\");", source)
        self.assertIn("function updateChatScrollFollowState()", source)
        self.assertIn("stickToBottomRef.current = isNearScrollBottom(element);", source)
        self.assertIn("if (!visibleTranscript.length || !stickToBottomRef.current) return;", source)
        self.assertIn("window.requestAnimationFrame(() => {", source)
        self.assertIn("element.scrollTop = element.scrollHeight;", source)
        self.assertIn('<div className="chat" ref={chatScrollRef} onScroll={updateChatScrollFollowState}>', source)


if __name__ == "__main__":
    unittest.main()
