import pathlib
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]
APP_TSX = ROOT / "frontend" / "src" / "app.tsx"
API_TS = ROOT / "frontend" / "src" / "lib" / "api.ts"
TRANSCRIPT_TSX = ROOT / "frontend" / "src" / "lib" / "transcript.tsx"
MARKDOWN_TSX = ROOT / "frontend" / "src" / "lib" / "markdown.tsx"
TYPES_TS = ROOT / "frontend" / "src" / "lib" / "types.ts"
STYLES_CSS = ROOT / "frontend" / "src" / "styles.css"


class NovaPreviewSourceTest(unittest.TestCase):
    def test_new_session_defaults_to_tmux_when_available(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("setNewSessionTmux(tmuxAvailable);", source)
        self.assertIn("create_in_tmux: tmuxAvailable && newSessionTmux", source)

    def test_new_session_selection_updates_ref_before_send(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("function selectSession(sessionId: string) {", source)
        self.assertIn("selectedSessionRef.current = sessionId;", source)
        self.assertIn("selectSession(found.session_id);", source)

    def test_new_session_dialog_closes_before_background_follow(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("const composerInputRef = useRef<HTMLTextAreaElement | null>(null);", source)
        self.assertIn("function focusComposerInput()", source)
        self.assertIn("async function followCreatedSession(brokerPid: number)", source)
        self.assertIn("setNewSessionOpen(false);\n      void followCreatedSession(result.broker_pid)", source)
        self.assertIn("ref={composerInputRef}", source)

    def test_rename_session_control_is_wired_to_api(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        api_source = API_TS.read_text(encoding="utf-8")
        self.assertIn("renameSession(sessionId: string, name: string)", api_source)
        self.assertIn("/rename", api_source)
        self.assertIn("function openRenameDialog(targetSession = selectedSession)", app_source)
        self.assertIn("const [renameSessionId, setRenameSessionId] = useState(\"\");", app_source)
        self.assertIn("const renameTargetSession = useMemo(", app_source)
        self.assertIn("setRenameSessionId(targetSession.session_id);", app_source)
        self.assertIn("void handleRenameSession()", app_source)
        self.assertIn('className="icon-btn"', app_source)
        self.assertIn('{icon("edit")}', app_source)
        self.assertNotIn("<span>Rename</span>", app_source)
        self.assertIn('title={selectedSession ? "Rename session" : "No session selected"}', app_source)

    def test_send_has_visible_pending_state_and_busy_queue_path(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        transcript_source = TRANSCRIPT_TSX.read_text(encoding="utf-8")
        self.assertIn("const [sending, setSending] = useState(false);", source)
        self.assertIn('type BusySubmitMode = "queue" | "interrupt";', source)
        self.assertIn("const [busySubmitMode, setBusySubmitMode] = useState<BusySubmitMode>(() => readBusySubmitMode());", source)
        self.assertIn("function mergeTranscriptEvents(current: UiTranscriptEvent[], incoming: UiTranscriptEvent[])", transcript_source)
        self.assertIn("let localEvent: UiTranscriptEvent | null = null;", source)
        self.assertIn("if (!shouldQueue) {\n      localEvent = {", source)
        self.assertIn('id: `local-user-${Date.now()}`', source)
        self.assertIn('meta: "sending"', source)
        self.assertNotIn('meta: shouldQueue ? "queued" : "sending"', source)
        self.assertIn("const composerSessionBusy = Boolean(awaitingAssistantReply || busy || selectedSession?.busy);", source)
        self.assertIn('const shouldQueue = composerSessionBusy && busySubmitMode === "queue";', source)
        self.assertIn('const shouldInterrupt = composerSessionBusy && busySubmitMode === "interrupt";', source)
        self.assertIn("await api.enqueueMessage(sessionId, text);", source)
        self.assertNotIn("meta: `queued${response.queue_len", source)
        self.assertIn("if (shouldInterrupt) await api.interrupt(sessionId);", source)
        self.assertIn("await api.sendMessage(sessionId, text);", source)
        self.assertIn("function handleComposerKeyDown(event: KeyboardEvent)", source)
        self.assertIn('if (event.key !== "Enter" || event.shiftKey || event.isComposing) return;', source)
        self.assertIn("event.preventDefault();\n    void handleSend();", source)
        self.assertIn("onKeyDown={handleComposerKeyDown}", source)
        self.assertIn('aria-label="Busy send mode"', source)
        self.assertIn('onClick={() => setBusySubmitMode("queue")}', source)
        self.assertIn('onClick={() => setBusySubmitMode("interrupt")}', source)
        self.assertIn('title={sending ? "Sending…" : composerSessionBusy && busySubmitMode === "queue" ? "Queue" : composerSessionBusy ? "Interrupt and send" : "Send"}', source)
        self.assertIn("disabled={sending || !selectedSessionId}", source)

    def test_queue_preview_renders_above_composer(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn("const queuePreviewItems = useMemo(() => queueItems.slice(0, 3), [queueItems]);", source)
        self.assertIn("setQueueLen(items.length);", source)
        self.assertIn("void loadQueue(sessionId);", source)
        self.assertIn("function openQueueModal()", source)
        self.assertIn('className="queuePreview"', source)
        self.assertIn("<span>Queued messages</span>", source)
        self.assertIn('{queuePreviewItems.map((item, index) => (', source)
        self.assertIn('onClick={() => openQueueModal()}', source)
        self.assertIn(".queuePreview {\n  width: min(920px, 100%);", css_source)
        self.assertIn(".queuePreviewItem {\n  display: grid;", css_source)

    def test_transcript_renders_markdown_blocks(self) -> None:
        transcript_source = TRANSCRIPT_TSX.read_text(encoding="utf-8")
        markdown_source = MARKDOWN_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn('import { MarkdownBlock } from "./markdown";', transcript_source)
        self.assertNotIn('import { PretextParagraph } from "./pretext";', transcript_source)
        self.assertIn('className="message-body markdown-body"', transcript_source)
        self.assertIn("export function markdownToHtml(text: string)", markdown_source)
        self.assertIn("function renderInlineMarkdown(value: string): string", markdown_source)
        self.assertIn("function renderTable(lines: string[], start: number)", markdown_source)
        self.assertIn("function blockquoteLine(line: string)", markdown_source)
        self.assertIn('out.push(`<blockquote>${renderMarkdownBlocks(quoteLines.join("\\n"))}</blockquote>`);', markdown_source)
        self.assertIn('return `<pre><code${langAttr}>${escapeHtml(chunk.value)}</code></pre>`;', markdown_source)
        self.assertIn('dangerouslySetInnerHTML={{ __html: markdownToHtml(text) }}', markdown_source)
        self.assertIn(".markdown-body h1,\n.markdown-body h2,", css_source)
        self.assertIn(".markdown-body blockquote {\n  border-left: 3px solid var(--border);", css_source)
        self.assertIn(".markdown-body pre code {\n  display: block;", css_source)
        self.assertIn(".md-table-wrap {\n  max-width: 100%;", css_source)

    def test_close_session_control_uses_delete_api(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        api_source = API_TS.read_text(encoding="utf-8")
        self.assertIn("deleteSession(sessionId: string)", api_source)
        self.assertIn("/delete", api_source)
        self.assertIn("async function handleCloseSession(targetSession = selectedSession)", app_source)
        self.assertIn("await api.deleteSession(sessionId);", app_source)
        self.assertIn('title={selectedSession ? "Close session" : "No session selected"}', app_source)
        self.assertIn('className="icon-btn danger"', app_source)

    def test_tmux_copy_handles_missing_clipboard_api(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("function copyTextViaSelection(text: string)", source)
        self.assertIn('typeof document.execCommand !== "function"', source)
        self.assertIn('document.execCommand("copy")', source)
        self.assertIn("async function copyToClipboard(text: string)", source)
        self.assertIn("navigator.clipboard && typeof navigator.clipboard.writeText === \"function\"", source)
        self.assertIn("await copyToClipboard(tmuxCommand);", source)
        self.assertNotIn("await navigator.clipboard.writeText(tmuxCommand);", source)
        self.assertIn('title={tmuxCommand || "No tmux attach command for this session"}', source)
        self.assertIn('{icon("terminal")}', source)
        self.assertEqual(source.count('{icon("tmux")}'), 0)

    def test_topbar_tool_toggle_uses_wrench_icon(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn('case "wrench":', source)
        self.assertIn('title={showTools ? "Hide tool calls" : "Show tool calls"}', source)
        self.assertIn('{icon("wrench")}', source)
        self.assertIn("setShowTools((current) => !current)", source)

    def test_topbar_uses_stable_session_status_not_polling_label(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("const topSessionStatus = useMemo(() => {", source)
        self.assertIn('if (queueLen) return `queue ${queueLen}`;', source)
        self.assertIn('if (awaitingAssistantReply || busy || selectedSession.busy) return "working";', source)
        self.assertIn('if (sessionIsStarting(selectedSession)) return "starting";', source)
        self.assertIn('const topSessionStatusClass = topSessionStatus === "working" || topSessionStatus === "starting" ? "status-chip working" : "status-chip";', source)
        self.assertIn('<span className={topSessionStatusClass}>{topSessionStatus}</span>', source)
        self.assertNotIn("connectionLabel", source)
        self.assertNotIn("loading transcript", source)

    def test_topbar_sidebar_toggle_collapses_left_navigation(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn("const [sidebarCollapsed, setSidebarCollapsed] = useState(false);", app_source)
        self.assertIn('sidebarCollapsed ? " sidebarCollapsed" : ""', app_source)
        self.assertIn('title={sidebarCollapsed ? "Show sidebar" : "Hide sidebar"}', app_source)
        self.assertIn("aria-pressed={sidebarCollapsed}", app_source)
        self.assertIn("onClick={() => setSidebarCollapsed((current) => !current)}", app_source)
        self.assertNotIn('title="Sidebar structure now follows the legacy station" disabled', app_source)
        self.assertIn(".app.sidebarCollapsed,\n.app.sidebarCollapsed.withRail {\n  grid-template-columns: minmax(0, 1fr);", css_source)
        self.assertIn(".app.sidebarCollapsed .sidebar {\n  display: none;", css_source)

    def test_settings_can_edit_codex_config_toml(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        api_source = API_TS.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn("CodexConfigResponse", api_source)
        self.assertIn('"/api/settings/codex_config"', api_source)
        self.assertIn("fetchCodexConfig(): Promise<CodexConfigResponse>", api_source)
        self.assertIn("saveCodexConfig(text: string): Promise<CodexConfigResponse>", api_source)
        self.assertIn("const [codexConfig, setCodexConfig] = useState<CodexConfigResponse | null>(null);", app_source)
        self.assertIn("const [codexConfigText, setCodexConfigText] = useState(\"\");", app_source)
        self.assertIn("const [settingsLoadError, setSettingsLoadError] = useState(\"\");", app_source)
        self.assertIn("const displayedVoiceSettings = voiceSettings || EMPTY_VOICE_SETTINGS;", app_source)
        self.assertIn("const settingsInitialLoading = voiceSettingsLoading && !voiceSettings && !codexConfig;", app_source)
        self.assertIn("const [voiceResult, notificationsResult, configResult] = await Promise.allSettled(", app_source)
        self.assertIn("void syncMobilePushState(loadedNotifications, loadedVoice.notifications.vapid_public_key);", app_source)
        self.assertIn("setSettingsLoadError(errors.join(\" · \"));", app_source)
        self.assertIn("{settingsInitialLoading ? (", app_source)
        self.assertIn("settingsLoadError ? (", app_source)
        self.assertIn("Retry", app_source)
        self.assertIn("async function reloadCodexConfig()", app_source)
        self.assertIn("async function saveCodexConfig()", app_source)
        self.assertIn('await api.saveCodexConfig(codexConfigText);', app_source)
        self.assertIn("<div className=\"detailSectionHeader\">Codex config.toml</div>", app_source)
        self.assertIn('className="settingsPath"', app_source)
        self.assertIn('className="configTextarea"', app_source)
        self.assertIn("Save config.toml", app_source)
        self.assertIn(".configTextarea {\n  min-height: 280px;", css_source)
        self.assertIn(".settingsPath {\n  padding: 8px 10px;", css_source)

    def test_settings_can_switch_between_dark_and_light_theme(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn('const THEME_MODE_KEY = "codoxear.nova.theme";', app_source)
        self.assertIn('type ThemeMode = "dark" | "light";', app_source)
        self.assertIn("function readThemeMode(): ThemeMode", app_source)
        self.assertIn("const [themeMode, setThemeMode] = useState<ThemeMode>(() => readThemeMode());", app_source)
        self.assertIn("document.documentElement.dataset.theme = themeMode;", app_source)
        self.assertIn('writeLocalStorage(THEME_MODE_KEY, themeMode === "light" ? "light" : null);', app_source)
        self.assertIn('<div className="detailSectionHeader">Appearance</div>', app_source)
        self.assertIn('className={`themeChoice${themeMode === "dark" ? " active" : ""}`}', app_source)
        self.assertIn('onClick={() => setThemeMode("light")}', app_source)
        self.assertIn(':root[data-theme="light"] {', css_source)
        self.assertIn("--bg: #e9eef5;", css_source)
        self.assertIn(':root[data-theme="light"] body {\n  background: var(--bg);', css_source)
        self.assertIn(".themePicker {\n  display: grid;", css_source)
        self.assertIn(':root[data-theme="light"] .sidebar,\n:root[data-theme="light"] .detailRail,', css_source)

    def test_sidebar_footer_does_not_show_help_button(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertNotIn("helpOpen", app_source)
        self.assertNotIn("setHelpOpen", app_source)
        self.assertNotIn('{icon("help")}', app_source)
        self.assertNotIn(">Help<", app_source)
        self.assertNotIn(".helpGrid", css_source)

    def test_new_session_working_status_marks_startup_and_awaiting_reply(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn("function sessionIsStarting(session: SessionSummary | null)", app_source)
        self.assertIn('if (sessionIsStarting(session)) return "starting";', app_source)
        self.assertIn("const awaitingAssistantReply = useMemo(() => {", app_source)
        self.assertIn("return latestUserTs > latestAssistantTs;", app_source)
        self.assertIn("session.busy || sessionIsStarting(session) ? \"running\" : \"idle\"", app_source)
        self.assertIn(".status-chip.working", css_source)

    def test_sidebar_preview_uses_latest_user_message(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        transcript_source = TRANSCRIPT_TSX.read_text(encoding="utf-8")
        self.assertIn("function previewFromEvents(events: UiTranscriptEvent[])", transcript_source)
        self.assertIn('if (event.kind !== "user") continue;', transcript_source)
        self.assertNotIn('if (event.kind !== "user" && event.kind !== "assistant") continue;', transcript_source)
        self.assertIn("setSessionLastLines((current) => ({ ...current, [sessionId]: previewFromEvents(nextEvents) || current[sessionId] || \"\" }));", source)
        self.assertIn("setSessionLastLines((prev) => ({ ...prev, [sessionId]: previewFromEvents(merged) || prev[sessionId] || \"\" }));", source)

    def test_sidebar_workspaces_and_sessions_are_draggable_and_persist_order(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn('const SIDEBAR_WORKSPACE_ORDER_KEY = "codoxear.nova.sidebar.workspaceOrder";', app_source)
        self.assertIn('const SIDEBAR_SESSION_ORDER_KEY = "codoxear.nova.sidebar.sessionOrder";', app_source)
        self.assertIn("function applyStoredOrder<T>(items: T[], order: string[], keyForItem: (item: T) => string)", app_source)
        self.assertIn("function moveOrderedKey(keys: string[], source: string, target: string)", app_source)
        self.assertIn("const [workspaceOrder, setWorkspaceOrder] = useState<string[]>(() => readStoredStringList(SIDEBAR_WORKSPACE_ORDER_KEY));", app_source)
        self.assertIn("const [sessionOrderByWorkspace, setSessionOrderByWorkspace] = useState<SidebarSessionOrder>(() => readStoredSessionOrder());", app_source)
        self.assertIn("applyStoredOrder(fallbackSortedGroups, workspaceOrder, (group) => group.key)", app_source)
        self.assertIn("sessions: applyStoredOrder(group.sessions, sessionOrderByWorkspace[group.key] || [], (session) => session.session_id)", app_source)
        self.assertIn("function handleWorkspaceDragStart(event: SidebarDragEvent, workspaceKey: string)", app_source)
        self.assertIn("function handleWorkspaceDrop(event: SidebarDragEvent, targetWorkspaceKey: string)", app_source)
        self.assertIn("function handleSessionDragStart(event: SidebarDragEvent, workspaceKey: string, sessionId: string)", app_source)
        self.assertIn("function handleSessionDrop(event: SidebarDragEvent, workspaceKey: string, targetSessionId: string)", app_source)
        self.assertIn("writeLocalStorage(SIDEBAR_WORKSPACE_ORDER_KEY, JSON.stringify(workspaceOrder));", app_source)
        self.assertIn("writeLocalStorage(SIDEBAR_SESSION_ORDER_KEY, JSON.stringify(sessionOrderByWorkspace));", app_source)
        self.assertIn("draggable\n                  onDragStart={(event) => handleWorkspaceDragStart(event, group.key)}", app_source)
        self.assertIn("draggable\n                          onDragStart={(event) => handleSessionDragStart(event, group.key, session.session_id)}", app_source)
        self.assertIn('.workspaceGroup[draggable="true"],\n.workspace[draggable="true"] {\n  cursor: grab;', css_source)
        self.assertIn(".workspaceGroup.is-dragging,\n.workspace.is-dragging {\n  opacity: 0.52;", css_source)

    def test_sidebar_session_context_menu_exposes_session_actions(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn("type SidebarContextMenuEvent = JSX.TargetedMouseEvent<HTMLElement>;", app_source)
        self.assertIn("const [sessionContextMenu, setSessionContextMenu] = useState<{ sessionId: string; x: number; y: number } | null>(null);", app_source)
        self.assertIn("const contextMenuSession = useMemo(", app_source)
        self.assertIn("function openSessionContextMenu(event: SidebarContextMenuEvent, session: SessionSummary)", app_source)
        self.assertIn("setSessionContextMenu({ sessionId: session.session_id, x: event.clientX, y: event.clientY });", app_source)
        self.assertIn("function focusSidebarSession(sessionId: string)", app_source)
        self.assertIn("onContextMenu={(event) => openSessionContextMenu(event, session)}", app_source)
        self.assertIn('className="sessionContextMenu"', app_source)
        self.assertIn("openRenameDialog(contextMenuSession)", app_source)
        self.assertIn("setShowDetailsPanel(true);", app_source)
        self.assertIn("setShowFilesPanel(true);", app_source)
        self.assertIn("void handleInterrupt(contextMenuSession)", app_source)
        self.assertIn("copyToClipboard(tmuxAttachCommandForSession(contextMenuSession))", app_source)
        self.assertIn("void handleCloseSession(contextMenuSession)", app_source)
        self.assertIn(".sessionContextMenu {\n  position: fixed;", css_source)
        self.assertIn(".sessionContextMenu .dangerText {\n  color: var(--danger);", css_source)

    def test_tool_events_default_to_collapsed(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        transcript_source = TRANSCRIPT_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn("function isCollapsibleEvent(kind: UiTranscriptEvent[\"kind\"])", transcript_source)
        self.assertIn("function stripRepeatedTitlePrefix(preview: string, title: string)", transcript_source)
        self.assertIn("return stripRepeatedTitlePrefix(preview, event.title);", transcript_source)
        self.assertIn("const knownToolTitles = new Map<string, string>();", transcript_source)
        self.assertIn('event.type !== "tool" || !event.tool_call_id', transcript_source)
        self.assertIn("knownToolTitles.set(event.tool_call_id, event.name.trim());", transcript_source)
        self.assertIn('const toolTitle = raw.type === "tool_result" ? knownName || (rawName === "tool" ? "" : rawName) : rawName;', transcript_source)
        self.assertIn('title: toolTitle || (raw.type === "tool_result" ? "Tool result" : "Tool call")', transcript_source)
        self.assertIn("function transcriptEventCollapsed(event: UiTranscriptEvent, collapsedState = collapsedEvents)", app_source)
        self.assertIn("return askUserDefaultsOpen(event) ? collapsedState[event.id] === true : collapsedState[event.id] !== false;", app_source)
        self.assertIn("setCollapsedEvents((current) => ({ ...current, [event.id]: !transcriptEventCollapsed(event, current) }));", app_source)
        self.assertIn("setCollapsedEvents({});", app_source)
        self.assertIn("const collapsed = transcriptEventCollapsed(event);", app_source)
        self.assertIn('className={`message-side${showMessageSide && !collapsible ? "" : " is-hidden"}`}', transcript_source)
        self.assertIn("showMessageSide && !collapsible ? ", transcript_source)
        self.assertIn('<div className="message-inline">', transcript_source)
        self.assertIn('<span className="message-fold" aria-label="Show details" title="Show details" />', transcript_source)
        self.assertNotIn("message-time-end", transcript_source)
        self.assertIn('<div className="message-inline is-open">', transcript_source)
        self.assertIn('<span className="message-fold is-open" aria-label="Hide details" title="Hide details" />', transcript_source)
        self.assertNotIn('{">"}</span>', transcript_source)
        self.assertNotIn('<span className="message-fold">Expand</span>', transcript_source)
        self.assertNotIn('<span className="message-fold">Collapse</span>', transcript_source)
        self.assertIn(".msg {\n  width: 100%;\n  display: grid;", css_source)
        self.assertIn("border-top: 0;\n  overflow-wrap: anywhere;", css_source)
        self.assertIn(".event-user + .event-assistant,\n.event-assistant + .event-user {\n  border-top: 1px solid rgba(15, 23, 42, 0.08);", css_source)
        self.assertIn(".event-tool,\n.event-result,\n.event-question {\n  padding: 8px 0;", css_source)
        self.assertNotIn(".event-tool + .event-tool", css_source)
        self.assertIn(".event-tool.is-collapsed,\n.event-result.is-collapsed,\n.event-question.is-collapsed {\n  align-items: center;\n  padding: 4px 0;", css_source)
        self.assertIn(".event-tool .message-main,\n.event-result .message-main,\n.event-question .message-main {\n  padding: 6px 0;\n  border-left: 0;\n  background: transparent;", css_source)
        self.assertIn(".event-tool .message-kind,\n.event-result .message-kind,\n.event-question .message-kind {\n  background: transparent;", css_source)
        self.assertIn(".is-collapsible:hover .message-main {\n  background: transparent;", css_source)
        self.assertIn(".is-collapsible {\n  cursor: pointer;\n}", css_source)
        self.assertNotIn("grid-template-columns: 64px minmax(0, 1fr);", css_source)
        self.assertIn(".event-question .message-main {\n  background: transparent;", css_source)
        self.assertIn(".is-collapsed .message-side {\n  display: none;", css_source)
        self.assertIn(".is-collapsible .message-side {\n  visibility: hidden;", css_source)
        self.assertIn(".is-collapsible .message-main,\n.is-collapsed .message-main {\n  grid-column: 2;\n  border-left: 0;", css_source)
        self.assertIn(".is-collapsed .message-main {\n  padding: 2px 0;", css_source)
        self.assertIn(".message-inline {\n  display: flex;", css_source)
        self.assertIn(".message-inline .message-fold {\n  position: relative;\n  width: 16px;\n  min-height: 16px;\n  padding: 0;\n  border: 0;\n  background: transparent;", css_source)
        self.assertNotIn("background: rgba(11, 15, 20, 0.52);", css_source)
        self.assertNotIn("background: rgba(255, 255, 255, 0.72);", css_source)
        self.assertIn(":root[data-theme=\"light\"] .event-tool .message-kind,\n:root[data-theme=\"light\"] .event-result .message-kind,\n:root[data-theme=\"light\"] .event-question .message-kind {\n  background: transparent;", css_source)
        self.assertIn('.message-inline .message-fold::before {\n  content: "";', css_source)
        self.assertIn("border-right: 1.5px solid currentColor;\n  border-bottom: 1.5px solid currentColor;", css_source)
        self.assertIn(".message-inline .message-fold.is-open::before {\n  top: 6px;\n  transform: rotate(225deg);", css_source)
        self.assertIn(".message-inline.is-open {\n  margin-bottom: 6px;", css_source)
        self.assertIn(".message-inline .message-summary {\n  min-width: 0;\n  flex: 1 1 auto;", css_source)
        self.assertIn(".message-summary {\n  overflow: hidden;", css_source)

    def test_ask_user_rows_can_be_answered_from_transcript(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        transcript_source = TRANSCRIPT_TSX.read_text(encoding="utf-8")
        types_source = TYPES_TS.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn("export type UiAskUserQuestion = {", types_source)
        self.assertIn("askOptions?: AskUserOption[];", types_source)
        self.assertIn("askQuestions?: UiAskUserQuestion[];", types_source)
        self.assertIn("function AskUserPrompt(props: {", transcript_source)
        self.assertIn("function answerTextForAskUser(event: UiTranscriptEvent, values: string[], freeform: string, bridgeAnswers: Record<string, string | string[]>)", transcript_source)
        self.assertIn("void submit([value], \"\");", transcript_source)
        self.assertIn('placeholder="Type an answer"', transcript_source)
        self.assertIn('event.kind === "ask_user" ? <AskUserPrompt event={event} onRespond={onAskUserRespond} /> : null', transcript_source)
        self.assertIn("async function handleAskUserRespond(event: UiTranscriptEvent, text: string)", app_source)
        self.assertIn("await api.sendMessage(sessionId, text);", app_source)
        self.assertIn("onAskUserRespond={handleAskUserRespond}", app_source)
        self.assertIn("function askUserDefaultsOpen(event: UiTranscriptEvent)", app_source)
        self.assertIn(".ask-user-options {\n  display: flex;", css_source)
        self.assertIn(".ask-user-option.is-selected", css_source)
        self.assertIn(".ask-user-composer {\n  display: grid;", css_source)

    def test_extension_progress_events_render_as_structured_transcript_rows(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        transcript_source = TRANSCRIPT_TSX.read_text(encoding="utf-8")
        types_source = TYPES_TS.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn('type: "extension";', types_source)
        self.assertIn('kind: "user" | "assistant" | "tool" | "tool_result" | "ask_user" | "extension";', types_source)
        self.assertIn('if (raw.type === "extension")', transcript_source)
        self.assertIn('kind: "extension"', transcript_source)
        self.assertIn("function ExtensionProgress(props: { event: UiTranscriptEvent })", transcript_source)
        self.assertIn('<div className="extension-progress"', transcript_source)
        self.assertIn('<ol className="extension-items">', transcript_source)
        self.assertIn('case "extension":\n      return "event-extension";', transcript_source)
        self.assertIn('event.kind === "user" || event.kind === "assistant" || event.kind === "extension"', app_source)
        self.assertIn(".extension-progress-bar", css_source)
        self.assertIn(".extension-item.is-in-progress .extension-item-mark", css_source)

    def test_assistant_messages_are_coalesced_and_not_background_filled(self) -> None:
        app_source = APP_TSX.read_text(encoding="utf-8")
        transcript_source = TRANSCRIPT_TSX.read_text(encoding="utf-8")
        css_source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn("function coalesceAdjacentAssistantEvents(events: UiTranscriptEvent[])", transcript_source)
        self.assertIn("function shouldShowMessageSide(events: UiTranscriptEvent[], index: number)", transcript_source)
        self.assertIn("meta: String(raw.message_class || \"\"),", transcript_source)
        self.assertNotIn("raw.notification_text === \"string\" && raw.notification_text.trim() ? raw.notification_text", transcript_source)
        self.assertIn("function isAssistantNarration(event: UiTranscriptEvent)", transcript_source)
        self.assertIn('return event.kind === "assistant" && event.meta.trim() === "narration";', transcript_source)
        self.assertIn("function shouldShowMessageFooter(events: UiTranscriptEvent[], index: number, collapsible: boolean)", transcript_source)
        self.assertIn("if (!event || collapsible || (!event.meta && !event.ts)) return false;", transcript_source)
        self.assertIn("if (!isAssistantNarration(event)) return true;", transcript_source)
        self.assertIn('if (next.kind === "user") return true;', transcript_source)
        self.assertIn("if (isAssistantNarration(next)) return false;", transcript_source)
        self.assertIn('second: "2-digit"', transcript_source)
        self.assertIn('previous.kind === "assistant" && event.kind === "assistant"', transcript_source)
        self.assertIn('if (previous.kind === "user") return true;', transcript_source)
        self.assertIn('if (previous.kind === "assistant") return false;', transcript_source)
        self.assertIn("function joinAssistantBodies(left: string, right: string)", transcript_source)
        self.assertIn("body: joinAssistantBodies(previous.body, event.body)", transcript_source)
        self.assertNotIn('body: [previous.body, event.body].filter((value) => value.trim()).join("\\n\\n")', transcript_source)
        self.assertIn("return out;", transcript_source)
        self.assertIn("return current\n    .filter((event) => !incomingIds.has(event.id))", transcript_source)
        self.assertIn("() =>\n      coalesceAdjacentAssistantEvents(", app_source)
        self.assertIn('event.kind === "user" || event.kind === "assistant" || event.kind === "extension"', app_source)
        self.assertIn("const showMessageSide = shouldShowMessageSide(events, index);", transcript_source)
        self.assertIn("const showMessageFooter = shouldShowMessageFooter(events, index, collapsible);", transcript_source)
        self.assertIn('className={`message-side${showMessageSide && !collapsible ? "" : " is-hidden"}`}', transcript_source)
        self.assertIn('<div className="message-footer">', transcript_source)
        self.assertIn("{collapsible && event.meta ? <div className=\"message-meta\">{event.meta}</div> : null}", transcript_source)
        self.assertIn("showMessageFooter ? (", transcript_source)
        self.assertIn('{event.meta ? <span className="message-meta">{event.meta}</span> : null}', transcript_source)
        self.assertIn('<span className="message-time">{formatTime(event.ts)}</span>', transcript_source)
        self.assertIn(".event-user .message-main,\n.event-assistant .message-main {\n  padding: 2px 0;\n  border-left: 0;", css_source)
        self.assertIn(".event-user .message-main {\n  border-radius: 8px;\n  background: rgba(37, 99, 235, 0.06);", css_source)
        self.assertIn(".msg {\n  width: 100%;\n  display: grid;\n  grid-template-columns: 118px minmax(0, 1fr) 118px;", css_source)
        self.assertIn(".event-user .message-side {\n  grid-column: 3;\n  align-items: flex-end;\n  text-align: right;", css_source)
        self.assertIn(".event-user .message-main {\n  grid-column: 2;\n  grid-row: 1;", css_source)
        self.assertIn(".event-user .message-side {\n    grid-column: 1;\n    grid-row: 1;\n    justify-content: flex-end;", css_source)
        self.assertIn(".event-user .message-main {\n    grid-column: 1;\n    grid-row: 2;", css_source)
        self.assertNotIn("border-left-color: rgba(37, 99, 235, 0.32);", css_source)
        self.assertIn(".event-assistant .message-main {\n  border-left: 0;\n  background: transparent;\n  padding: 2px 0;", css_source)
        self.assertIn(".status-chip {\n  background: rgba(15, 23, 42, 0.08);", css_source)
        self.assertNotIn(".status-chip,\n.message-kind {\n  background:", css_source)
        self.assertIn(":root[data-theme=\"light\"] .event-user .message-kind {\n  color: #1d4ed8;\n  background: transparent;", css_source)
        self.assertIn(":root[data-theme=\"light\"] .event-assistant .message-kind {\n  color: #0f172a;\n  background: transparent;", css_source)
        self.assertIn(".message-footer {\n  display: flex;\n  align-items: baseline;\n  justify-content: flex-start;\n  gap: 8px;\n  margin-top: 8px;", css_source)
        self.assertNotIn(".message-time-end", css_source)
        self.assertIn(".message-side.is-hidden {\n  visibility: hidden;", css_source)

    def test_composer_layout_is_pinned_outside_scroll_region(self) -> None:
        source = STYLES_CSS.read_text(encoding="utf-8")
        self.assertIn(".main {\n  display: flex;\n  flex-direction: column;", source)
        self.assertIn(".workspaceBody {\n  flex: 1 1 auto;", source)
        self.assertIn("  overflow: hidden;\n}\n\n.detailRail", source)
        self.assertIn(".chatWrap {\n  display: flex;", source)
        self.assertIn(".chat {\n  flex: 1 1 auto;", source)
        self.assertIn(".composer {\n  position: sticky;\n  bottom: 0;", source)
        self.assertIn("grid-template-rows: minmax(0, 1fr) minmax(160px, 38vh);", source)
        self.assertIn(".composerMode {\n  display: inline-flex;", source)
        self.assertIn(".modeBtn.active {\n  background: var(--accent-soft);", source)

    def test_transcript_autoscroll_respects_history_browsing(self) -> None:
        source = APP_TSX.read_text(encoding="utf-8")
        self.assertIn("const CHAT_BOTTOM_FOLLOW_THRESHOLD_PX = 96;", source)
        self.assertIn("function isNearScrollBottom(element: HTMLElement)", source)
        self.assertIn("element.scrollHeight - element.scrollTop - element.clientHeight <= CHAT_BOTTOM_FOLLOW_THRESHOLD_PX", source)
        self.assertIn("const chatScrollRef = useRef<HTMLDivElement | null>(null);", source)
        self.assertIn("const stickToBottomRef = useRef(true);", source)
        self.assertIn("const lastAutoScrollKeyRef = useRef(\"\");", source)
        self.assertIn("function updateChatScrollFollowState()", source)
        self.assertIn("stickToBottomRef.current = isNearScrollBottom(element);", source)
        self.assertIn("if (!visibleTranscript.length || !stickToBottomRef.current) return;", source)
        self.assertIn("window.requestAnimationFrame(() => {", source)
        self.assertIn("element.scrollTop = element.scrollHeight;", source)
        self.assertIn('<div className="chat" ref={chatScrollRef} onScroll={updateChatScrollFollowState}>', source)


if __name__ == "__main__":
    unittest.main()
